@echo off
REM  DO NOT EDIT: generated by scripts/build_scripts.py
REM    Sources: scripts/*.tmpl  +  scripts/_common.bat
REM    Regenerate with:  python scripts/build_scripts.py
REM ============================================================
REM install.bat - 零基础一键安装入口（Windows 10/11）
REM
REM !!! 本文件由 scripts/build_scripts.py 自动生成，请勿手动编辑 !!!
REM !!! 修改源：scripts/install.bat.tmpl + scripts/_common.bat  !!!
REM
REM 流程：winget 装 Python/Node/Git/Ollama → clone/定位源码 → 调 deploy.bat
REM 所有外部命令的完整输出会追加到 install.log；出错请把 install.log 发给维护者。
REM ============================================================

setlocal enabledelayedexpansion
chcp 65001 > nul
title ai-ppt-maker - 一键安装

set LOG=%~dp0install.log

REM --- 初始化日志 ---
echo ============================================================ > "%LOG%"
echo install.bat log - %DATE% %TIME% >> "%LOG%"
echo CWD: %CD% >> "%LOG%"
echo SCRIPT: %~f0 >> "%LOG%"
echo ============================================================ >> "%LOG%"
ver >> "%LOG%" 2>&1
echo. >> "%LOG%"

call :ui_banner "ai-ppt-maker - 一键安装" "Python + Node + Ollama 模型；首次预计 20-40 分钟"
call :ui_init 6

REM --- 0. winget ---
call :ui_step "检查 winget"
set "WINGET_EXE="
if exist "%LOCALAPPDATA%\Microsoft\WindowsApps\winget.exe" set "WINGET_EXE=%LOCALAPPDATA%\Microsoft\WindowsApps\winget.exe"
if not defined WINGET_EXE (
    for /f "delims=" %%W in ('where winget 2^>nul') do if not defined WINGET_EXE set "WINGET_EXE=%%W"
)
set HAVE_WINGET=0
if defined WINGET_EXE set HAVE_WINGET=1
if %HAVE_WINGET%==0 (
    call :ui_warn "未找到 winget。请到 Microsoft Store 搜 '应用安装程序' 安装"
    call :ui_ok_warn "winget 缺失（继续，但需要手动安装依赖）"
) else (
    "%WINGET_EXE%" --version >> "%LOG%" 2>&1
    call :ui_ok "winget OK"
)

REM --- 1. Python ---
call :ui_step "检查 Python"
call :find_python
if not defined PY_EXE (
    if %HAVE_WINGET%==1 (
        call :ui_info "winget install Python.Python.3.11（若弹出 UAC 请允许）..."
        "%WINGET_EXE%" install -e --id Python.Python.3.11 --accept-package-agreements --accept-source-agreements --silent >> "%LOG%" 2>&1
        if errorlevel 1 (
            call :ui_fail "winget 安装 Python 失败，详见 %LOG%"
            call :ui_summary
            pause & exit /b 1
        )
        call :refresh_path
        call :find_python
        if not defined PY_EXE (
            call :ui_fail "Python 已安装但本会话无法定位；请关闭重开 cmd"
            call :ui_summary
            pause & exit /b 1
        )
    ) else (
        call :ui_fail "未找到 Python 且 winget 不可用"
        call :ui_summary
        pause & exit /b 1
    )
)
for /f "tokens=2" %%v in ('"!PY_EXE!" --version 2^>^&1') do set PYVER=%%v
call :ui_ok "Python !PYVER!"

REM --- 2. Node.js ---
call :ui_step "检查 Node.js (>=18)"
where node >nul 2>nul
if errorlevel 1 (
    if %HAVE_WINGET%==1 (
        call :ui_info "winget install OpenJS.NodeJS.LTS ..."
        "%WINGET_EXE%" install -e --id OpenJS.NodeJS.LTS --accept-package-agreements --accept-source-agreements --silent >> "%LOG%" 2>&1
        if errorlevel 1 (
            call :ui_fail "winget 安装 Node.js 失败，详见 %LOG%"
            call :ui_summary
            pause & exit /b 1
        )
        call :refresh_path
        where node >nul 2>nul
        if errorlevel 1 (
            call :ui_fail "Node.js 已安装但 PATH 未生效；请关闭重开 cmd"
            call :ui_summary
            pause & exit /b 1
        )
    ) else (
        call :ui_fail "未找到 Node.js 且 winget 不可用，请从 https://nodejs.org 安装"
        call :ui_summary
        pause & exit /b 1
    )
)
for /f "delims=" %%v in ('node --version 2^>^&1') do set NODEVER=%%v
call :ui_ok "Node !NODEVER!"

REM --- 3. Git ---
call :ui_step "检查 Git"
where git >nul 2>nul
if errorlevel 1 (
    if %HAVE_WINGET%==1 (
        call :ui_info "winget install Git.Git ..."
        "%WINGET_EXE%" install -e --id Git.Git --accept-package-agreements --accept-source-agreements --silent >> "%LOG%" 2>&1
        if errorlevel 1 (
            call :ui_ok_warn "winget 安装 Git 失败（如源码已在本地可忽略）"
        ) else (
            call :refresh_path
            where git >nul 2>nul
            if errorlevel 1 (
                call :ui_ok_warn "Git 已安装但当前窗口 PATH 未生效"
            ) else (
                call :ui_ok
            )
        )
    ) else (
        call :ui_ok_warn "未找到 Git 且 winget 不可用，将跳过自动 clone"
    )
) else (
    git --version >> "%LOG%" 2>&1
    call :ui_ok
)

REM --- 4. Ollama ---
call :ui_step "检查 Ollama"
where ollama >nul 2>nul
if errorlevel 1 (
    if %HAVE_WINGET%==1 (
        call :ui_info "winget install Ollama.Ollama ..."
        "%WINGET_EXE%" install -e --id Ollama.Ollama --accept-package-agreements --accept-source-agreements --silent >> "%LOG%" 2>&1
        if errorlevel 1 (
            call :ui_ok_warn "winget 安装 Ollama 失败（M2 后才需要 LLM）"
        ) else (
            call :refresh_path
            where ollama >nul 2>nul
            if errorlevel 1 (
                call :ui_ok_warn "Ollama 已安装但 PATH 未生效"
            ) else (
                call :ui_ok
            )
        )
    ) else (
        call :ui_ok_warn "未找到 Ollama 且 winget 不可用"
    )
) else (
    ollama --version >> "%LOG%" 2>&1
    call :ui_ok
)

REM --- 5. 获取/定位源码 ---
call :ui_step "准备项目源码"
if exist "%~dp0backend\pyproject.toml" (
    set PROJ_DIR=%~dp0
    if "!PROJ_DIR:~-1!"=="\" set PROJ_DIR=!PROJ_DIR:~0,-1!
    call :ui_info "当前目录已是项目: !PROJ_DIR!"
) else (
    if defined APM_INSTALL_DIR (
        set PROJ_DIR=!APM_INSTALL_DIR!
    ) else (
        set PROJ_DIR=%USERPROFILE%\ai-ppt-maker
    )
    call :ui_info "安装目录: !PROJ_DIR!  (可用 APM_INSTALL_DIR 覆盖)"

    if exist "!PROJ_DIR!\backend\pyproject.toml" (
        call :ui_info "目录已有项目，执行 git pull ..."
        pushd "!PROJ_DIR!"
        git pull >> "%LOG%" 2>&1
        popd
    ) else (
        where git >nul 2>nul
        if errorlevel 1 (
            call :ui_fail "没有 git 且目标目录无源码，无法继续"
            call :ui_summary
            pause & exit /b 1
        )
        call :ui_info "git clone 到 !PROJ_DIR! ..."
        for %%D in ("!PROJ_DIR!") do if not exist "%%~dpD" md "%%~dpD"
        if not defined APM_REPO_URL set "APM_REPO_URL=https://example.com/REPLACE_ME/ai-ppt-maker.git"
        git clone "!APM_REPO_URL!" "!PROJ_DIR!" >> "%LOG%" 2>&1
        if errorlevel 1 (
            call :ui_fail "git clone 失败，详见 %LOG%（请设置 APM_REPO_URL 指向你的远端仓库）"
            call :ui_summary
            pause & exit /b 1
        )
    )
)
call :ui_ok

REM --- 6. 调用 deploy.bat ---
call :ui_step "部署 venv + 依赖 + 前端 + 拉模型"
cd /d "!PROJ_DIR!"
if not exist "scripts\deploy.bat" (
    call :ui_fail "找不到 scripts\deploy.bat，项目结构异常"
    call :ui_summary
    pause & exit /b 1
)
call "scripts\deploy.bat"
if errorlevel 1 (
    call :ui_fail "deploy.bat 执行失败，详见屏幕与 %LOG%"
    call :ui_summary
    pause & exit /b 1
)
call :ui_ok "deploy.bat 完成"

call :ui_summary

echo.
echo 项目位置: !PROJ_DIR!
echo 日常启动: 双击 !PROJ_DIR!\scripts\start.bat
echo 安装日志: %LOG%
echo.

if not defined APM_AUTO_START set APM_AUTO_START=1
if "!APM_AUTO_START!"=="1" (
    echo [i] 自动启动中...（设环境变量 APM_AUTO_START=0 可禁用）
    start "" "!PROJ_DIR!\scripts\start.bat"
) else (
    echo [i] 已跳过自动启动 (APM_AUTO_START=0)
)
pause
endlocal
exit /b 0

REM ============================================================
REM  >>>>>>>>>>>>>>>>  _common.bat 内容内联区  <<<<<<<<<<<<<<<<
REM ============================================================

:_common_inlined
REM ============================================================
REM scripts\_common.bat - Windows 安装/部署脚本共享函数库
REM
REM 专业安装器 UI（CMD 版）：
REM   step header N/M plus percent, single-line progress bar, elapsed seconds
REM   :ui_banner / :ui_step / :ui_ok / :ui_warn / :ui_fail / :ui_summary
REM
REM 系统工具：
REM   :refresh_path   - winget 安装后从注册表刷新本进程 PATH
REM   :find_python    - 跳过 Microsoft Store stub，定位真实 python.exe -> PY_EXE
REM
REM 所有全局变量以 _UI_ / _MS_ 开头，避免和调用者冲突。
REM
REM 约定：调用者 setlocal enabledelayedexpansion 后用 "call :ui_step ..." 调用；
REM       调用者通过 set LOG=... 指定日志文件。
REM
REM 本文件由 deploy.bat 直接 `call`。install.bat 由 scripts/build_install.py
REM 在打包时内联此文件的函数段，以满足"单文件一键安装"约束。
REM ============================================================

REM 被 call 时直接跳过函数定义区到 :_common_loaded 标签
goto :_common_loaded

REM ====================== UI: banner ======================
:ui_banner
REM %~1 = title, %~2 = subtitle (optional)
echo.
echo +------------------------------------------------------------+
echo ^|   %~1
if not "%~2"=="" echo ^|   %~2
echo +------------------------------------------------------------+
echo.
exit /b 0

REM ====================== UI: init ======================
:ui_init
REM %~1 = total steps
set "_UI_TOTAL=%~1"
set "_UI_CUR=0"
set "_UI_SUMMARY_FILE=%TEMP%\_ms_summary_%RANDOM%%RANDOM%.txt"
type nul > "%_UI_SUMMARY_FILE%" 2>nul
exit /b 0

REM ====================== UI: step ======================
:ui_step
REM %~1 = label
set /a _UI_CUR=_UI_CUR+1
set "_UI_CUR_LABEL=%~1"
set /a _UI_PCT=_UI_CUR*100/_UI_TOTAL
set "_UI_T0=%TIME%"
echo.
echo ^>^> [%_UI_CUR%/%_UI_TOTAL%] %~1 ^(%_UI_PCT%%%^)
call :_ui_progress_bar %_UI_PCT%
if defined LOG echo [STEP %TIME%] [%_UI_CUR%/%_UI_TOTAL%] %~1 >> "%LOG%"
exit /b 0

REM ====================== UI: progress bar ======================
:_ui_progress_bar
REM %~1 = pct (0-100)
set /a _UI_BAR_FILLED=%~1*30/100
set /a _UI_BAR_EMPTY=30-_UI_BAR_FILLED
set "_UI_BAR_STR="
for /l %%i in (1,1,%_UI_BAR_FILLED%) do set "_UI_BAR_STR=!_UI_BAR_STR!#"
for /l %%i in (1,1,%_UI_BAR_EMPTY%) do set "_UI_BAR_STR=!_UI_BAR_STR!-"
echo    [!_UI_BAR_STR!] %~1%%
exit /b 0

REM ====================== UI: ok ======================
:ui_ok
REM %~1 = optional note
call :_ui_elapsed
if "%~1"=="" (
    echo    [OK] done ^(!_UI_ELAPSED!s^)
) else (
    echo    [OK] %~1 ^(!_UI_ELAPSED!s^)
)
echo OK^|%_UI_CUR_LABEL%^|!_UI_ELAPSED! >> "%_UI_SUMMARY_FILE%"
if defined LOG echo [OK %TIME%] %_UI_CUR_LABEL% took !_UI_ELAPSED!s >> "%LOG%"
exit /b 0

REM ====================== UI: warn ======================
:ui_warn
echo    [!!] %~1
if defined LOG echo [WARN %TIME%] %~1 >> "%LOG%"
exit /b 0

REM ====================== UI: ok with warn ======================
:ui_ok_warn
call :_ui_elapsed
echo    [!!] %~1 ^(!_UI_ELAPSED!s^)
echo WARN^|%_UI_CUR_LABEL%^|!_UI_ELAPSED! >> "%_UI_SUMMARY_FILE%"
if defined LOG echo [WARN-OK %TIME%] %_UI_CUR_LABEL% took !_UI_ELAPSED!s >> "%LOG%"
exit /b 0

REM ====================== UI: fail ======================
:ui_fail
call :_ui_elapsed
echo    [X] %~1 ^(!_UI_ELAPSED!s^)
echo FAIL^|%_UI_CUR_LABEL%^|!_UI_ELAPSED! >> "%_UI_SUMMARY_FILE%"
if defined LOG echo [FAIL %TIME%] %_UI_CUR_LABEL% ^(%~1^) took !_UI_ELAPSED!s >> "%LOG%"
exit /b 0

REM ====================== UI: info ======================
:ui_info
echo    [i] %~1
if defined LOG echo [INFO %TIME%] %~1 >> "%LOG%"
exit /b 0

REM ====================== UI: summary ======================
:ui_summary
echo.
echo +------------------------------------------------------------+
echo ^|   部署摘要
echo +------------------------------------------------------------+
set "_UI_ANY_FAIL=0"
set "_UI_ANY_WARN=0"
if exist "%_UI_SUMMARY_FILE%" (
    for /f "usebackq tokens=1,2,3 delims=|" %%a in ("%_UI_SUMMARY_FILE%") do (
        if "%%a"=="OK"   echo    [OK] %%b ^(%%cs^)
        if "%%a"=="WARN" (echo    [!!] %%b ^(%%cs^) & set "_UI_ANY_WARN=1")
        if "%%a"=="FAIL" (echo    [X]  %%b ^(%%cs^) & set "_UI_ANY_FAIL=1")
    )
    del "%_UI_SUMMARY_FILE%" >nul 2>nul
)
echo.
if "!_UI_ANY_FAIL!"=="1" (
    echo [X] 部署存在失败步骤，请查看上方日志
    exit /b 1
)
if "!_UI_ANY_WARN!"=="1" (
    echo [!!] 部署完成（有警告）
    exit /b 0
)
echo [OK] 部署完成，一切就绪
exit /b 0

REM ====================== UI: elapsed helper ======================
:_ui_elapsed
if not defined _UI_T0 (set "_UI_ELAPSED=0" & exit /b 0)
call :_time_to_ms "%_UI_T0%" _UI_T0_MS
call :_time_to_ms "%TIME%"    _UI_T1_MS
set /a _UI_DIFF_MS=_UI_T1_MS-_UI_T0_MS
if !_UI_DIFF_MS! LSS 0 set /a _UI_DIFF_MS+=86400000
set /a _UI_ELAPSED=_UI_DIFF_MS/1000
exit /b 0

REM ====================== time parser: HH:MM:SS.cs -> ms ======================
:_time_to_ms
set "_TS=%~1"
for /f "tokens=1-4 delims=:., " %%a in ("%_TS%") do (
    set /a %~2=^(^(1%%a-100^)*3600 + ^(1%%b-100^)*60 + ^(1%%c-100^)^)*1000 + ^(1%%d-100^)*10
)
exit /b 0

REM ====================== system: PATH refresh from registry ======================
:refresh_path
set "_NEWPATH="
for /f "usebackq tokens=2*" %%A in (`reg query "HKLM\System\CurrentControlSet\Control\Session Manager\Environment" /v Path 2^>nul`) do set "_NEWPATH=%%B"
for /f "usebackq tokens=2*" %%A in (`reg query "HKCU\Environment" /v Path 2^>nul`) do set "_NEWPATH=!_NEWPATH!;%%B"
if defined _NEWPATH (
    set "PATH=!_NEWPATH!"
    if defined LOG echo [PATH-REFRESH %TIME%] done >> "%LOG%"
)
exit /b 0

REM ====================== system: find real Python ======================
:find_python
set "PY_EXE="
for /f "delims=" %%P in ('where python 2^>nul') do (
    if not defined PY_EXE (
        call :_is_real_python "%%P" _IS_REAL
        if "!_IS_REAL!"=="1" set "PY_EXE=%%P"
    )
)
if defined PY_EXE exit /b 0
where py >nul 2>nul
if not errorlevel 1 (
    for /f "delims=" %%P in ('py -3 -c "import sys;print(sys.executable)" 2^>nul') do if not defined PY_EXE set "PY_EXE=%%P"
)
if defined PY_EXE exit /b 0
for /d %%D in ("%LOCALAPPDATA%\Programs\Python\Python3*") do (
    if exist "%%D\python.exe" if not defined PY_EXE set "PY_EXE=%%D\python.exe"
)
exit /b 0

REM Judge if %~1 is a real Python (vs Microsoft Store 0-byte stub)
:_is_real_python
set "%~2=0"
echo %~1 | findstr /i "WindowsApps" >nul
if not errorlevel 1 (
    for %%F in ("%~1") do if %%~zF LEQ 1024 exit /b 0
)
set "%~2=1"
exit /b 0

REM ============================================================
REM 加载完成标签 —— 被 call 时从 goto :_common_loaded 跳到此处
REM ============================================================
:_common_loaded
exit /b 0
