"""scripts/build_scripts.py — 构建 install.bat / deploy.bat 单文件。

组合 *.tmpl 模板 + scripts/_common.bat 生成 scripts/install.bat、scripts/deploy.bat、scripts/cleanup.bat。

CI: `python scripts/build_scripts.py --check` 校验同步。
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COMMON = ROOT / "scripts" / "_common.bat"

TARGETS: list[tuple[Path, Path, str]] = [
    (ROOT / "scripts" / "install.bat.tmpl", ROOT / "scripts" / "install.bat", "_common_inlined"),
    (ROOT / "scripts" / "deploy.bat.tmpl",  ROOT / "scripts" / "deploy.bat", "_common_inlined"),
    (ROOT / "scripts" / "cleanup.bat.tmpl", ROOT / "scripts" / "cleanup.bat", "_common_inlined"),
]

HEADER_WARN = (
    "REM  DO NOT EDIT: generated by scripts/build_scripts.py\r\n"
    "REM    Sources: scripts/*.tmpl  +  scripts/_common.bat\r\n"
    "REM    Regenerate with:  python scripts/build_scripts.py\r\n"
)


def _extract_common_body(text: str) -> str:
    lines = text.splitlines()
    if lines and lines[0].strip().lower().startswith("@echo off"):
        lines = lines[1:]
    return "\n".join(lines).strip("\n")


def build_one(tmpl: Path, mark: str) -> str:
    tmpl_text = tmpl.read_text(encoding="utf-8")
    common_body = _extract_common_body(COMMON.read_text(encoding="utf-8"))
    rendered = tmpl_text.replace("{{COMMON_MARK}}", mark)
    rendered = rendered.replace("{{COMMON_BODY}}", common_body)
    lines = rendered.splitlines()
    out_lines: list[str] = []
    inserted = False
    for ln in lines:
        out_lines.append(ln)
        if not inserted and ln.strip().lower().startswith("@echo off"):
            out_lines.append(HEADER_WARN.rstrip("\r\n"))
            inserted = True
    rendered = "\n".join(out_lines) + "\n"
    rendered = rendered.replace("\r\n", "\n").replace("\n", "\r\n")
    return rendered


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="CI 校验同步")
    args = ap.parse_args()

    any_fail = False
    for tmpl, out_path, mark in TARGETS:
        generated = build_one(tmpl, mark)
        if args.check:
            if not out_path.exists():
                print(f"[FAIL] {out_path} 不存在", file=sys.stderr)
                any_fail = True
                continue
            existing = out_path.read_bytes().decode("utf-8", errors="replace")
            existing_norm = existing.replace("\r\n", "\n").replace("\n", "\r\n")
            if existing_norm != generated:
                print(
                    f"[FAIL] {out_path.relative_to(ROOT)} 与 {tmpl.name} + _common.bat 不同步\n"
                    f"       请运行: python scripts/build_scripts.py",
                    file=sys.stderr,
                )
                any_fail = True
            else:
                print(f"[OK]   {out_path.relative_to(ROOT)} 同步")
        else:
            out_path.write_bytes(generated.encode("utf-8"))
            print(f"[OK]   生成 {out_path.relative_to(ROOT)} ({len(generated.splitlines())} lines)")
    return 1 if any_fail else 0


if __name__ == "__main__":
    raise SystemExit(main())
