@echo off
REM  DO NOT EDIT: generated by scripts/build_scripts.py
REM    Sources: scripts/*.tmpl  +  scripts/_common.bat
REM    Regenerate with:  python scripts/build_scripts.py
REM ============================================================
REM scripts/cleanup.bat - Windows 一键卸载脚本
REM
REM !!! 本文件由 scripts/build_scripts.py 自动生成，请勿手动编辑 !!!
REM !!! 修改源：scripts/cleanup.bat.tmpl + scripts/_common.bat   !!!
REM
REM 默认清理：
REM   1. stop.bat
REM   2. backend\.venv 与 frontend\node_modules / dist
REM   3. 运行/构建产物（output, .pytest_cache, .run, *.log, __pycache__, *.egg-info）
REM
REM 可选：
REM   /with-model    额外删除 Ollama 模型
REM   /with-ollama   额外卸载 Ollama 二进制
REM   /purge         额外删除整个项目目录（不可逆）
REM
REM 安全：
REM   /dry-run       仅打印
REM   /yes           非交互
REM
REM 等价环境变量：APM_CLEAN_MODEL=1 / APM_CLEAN_OLLAMA=1 / APM_PURGE=1 / APM_CLEAN_YES=1 / APM_DRY_RUN=1
REM ============================================================

setlocal enabledelayedexpansion
chcp 65001 > nul
title ai-ppt-maker - 一键卸载

set "_SCRIPT_DIR=%~dp0"
if "%_SCRIPT_DIR:~-1%"=="\" set "_SCRIPT_DIR=%_SCRIPT_DIR:~0,-1%"
if exist "%_SCRIPT_DIR%\backend\pyproject.toml" (
    set "PROJ_ROOT=%_SCRIPT_DIR%"
) else if exist "%_SCRIPT_DIR%\..\backend\pyproject.toml" (
    for %%I in ("%_SCRIPT_DIR%\..") do set "PROJ_ROOT=%%~fI"
) else (
    echo [FATAL] 未找到 backend\pyproject.toml，请在项目目录下运行
    pause & exit /b 3
)

set "DRY_RUN=%APM_DRY_RUN%"
set "ASSUME_YES=%APM_CLEAN_YES%"
set "WITH_MODEL=%APM_CLEAN_MODEL%"
set "WITH_OLLAMA=%APM_CLEAN_OLLAMA%"
set "PURGE=%APM_PURGE%"
if "%DRY_RUN%"=="" set "DRY_RUN=0"
if "%ASSUME_YES%"=="" set "ASSUME_YES=0"
if "%WITH_MODEL%"=="" set "WITH_MODEL=0"
if "%WITH_OLLAMA%"=="" set "WITH_OLLAMA=0"
if "%PURGE%"=="" set "PURGE=0"

:parse_args
if "%~1"=="" goto :args_done
if /i "%~1"=="/dry-run" set "DRY_RUN=1" & shift & goto :parse_args
if /i "%~1"=="--dry-run" set "DRY_RUN=1" & shift & goto :parse_args
if /i "%~1"=="/yes" set "ASSUME_YES=1" & shift & goto :parse_args
if /i "%~1"=="-y" set "ASSUME_YES=1" & shift & goto :parse_args
if /i "%~1"=="--yes" set "ASSUME_YES=1" & shift & goto :parse_args
if /i "%~1"=="/with-model" set "WITH_MODEL=1" & shift & goto :parse_args
if /i "%~1"=="--with-model" set "WITH_MODEL=1" & shift & goto :parse_args
if /i "%~1"=="/with-ollama" set "WITH_OLLAMA=1" & shift & goto :parse_args
if /i "%~1"=="--with-ollama" set "WITH_OLLAMA=1" & shift & goto :parse_args
if /i "%~1"=="/purge" set "PURGE=1" & shift & goto :parse_args
if /i "%~1"=="--purge" set "PURGE=1" & shift & goto :parse_args
if /i "%~1"=="/h" goto :show_help
if /i "%~1"=="/?" goto :show_help
if /i "%~1"=="-h" goto :show_help
if /i "%~1"=="--help" goto :show_help
echo 未知参数: %~1
goto :show_help

:show_help
echo cleanup.bat [/dry-run] [/yes] [/with-model] [/with-ollama] [/purge]
endlocal & exit /b 0

:args_done

if "%PURGE%"=="1" (
    if /i "%PROJ_ROOT%"=="C:\" (
        echo [FATAL] 拒绝在 C:\ 上 purge
        endlocal & exit /b 3
    )
    if /i "%PROJ_ROOT%"=="%USERPROFILE%" (
        echo [FATAL] 拒绝在用户主目录上 purge
        endlocal & exit /b 3
    )
    findstr /b /c:"name = \"ai-ppt-maker-backend\"" "%PROJ_ROOT%\backend\pyproject.toml" >nul 2>nul
    if errorlevel 1 (
        echo [FATAL] %PROJ_ROOT% 不是 ai-ppt-maker，拒绝 /purge
        endlocal & exit /b 3
    )
)

call :ui_banner "ai-ppt-maker - 一键卸载" "项目: %PROJ_ROOT%"

echo   backend\.venv      : 检查中...
if exist "%PROJ_ROOT%\backend\.venv" (echo                       存在) else (echo                       不存在)
echo   frontend\node_modules : 检查中...
if exist "%PROJ_ROOT%\frontend\node_modules" (echo                          存在) else (echo                          不存在)
echo   选项: with-model=%WITH_MODEL% with-ollama=%WITH_OLLAMA% purge=%PURGE%
if "%DRY_RUN%"=="1" echo   模式: DRY-RUN
echo.

if not "%ASSUME_YES%"=="1" if not "%DRY_RUN%"=="1" (
    set /p "ANS=确认执行清理? [y/N] "
    if /i not "!ANS!"=="y" if /i not "!ANS!"=="yes" (
        echo 已取消
        endlocal & exit /b 0
    )
)

set "STEPS=4"
if "%WITH_MODEL%"=="1" set /a STEPS=STEPS+1
if "%WITH_OLLAMA%"=="1" set /a STEPS=STEPS+1
if "%PURGE%"=="1" set /a STEPS=STEPS+1
call :ui_init %STEPS%

REM --- 1. stop.bat ---
call :ui_step "停止运行中的服务"
if exist "%_SCRIPT_DIR%\stop.bat" (
    if "%DRY_RUN%"=="1" (call :ui_info "[DRY] call stop.bat") else (call "%_SCRIPT_DIR%\stop.bat" >nul 2>nul)
) else (
    call :ui_info "stop.bat 不存在，跳过"
)
call :ui_ok

REM --- 2. backend venv ---
call :ui_step "删除 backend\.venv"
call :_clean_dir "backend\.venv"
call :ui_ok

REM --- 3. frontend node_modules + dist ---
call :ui_step "删除 frontend\node_modules 与 frontend\dist"
call :_clean_dir "frontend\node_modules"
call :_clean_dir "frontend\dist"
call :ui_ok

REM --- 4. 运行与构建产物 ---
call :ui_step "删除运行/构建产物"
call :_clean_dir ".run"
call :_clean_dir ".pytest_cache"
call :_clean_dir "htmlcov"
call :_clean_file ".coverage"
call :_clean_file "coverage.xml"
call :_clean_file "install.log"
call :_clean_file "deploy.log"
if "%DRY_RUN%"=="1" (
    call :ui_info "[DRY] for /d /r ... __pycache__ / *.egg-info"
) else (
    for /d /r "%PROJ_ROOT%" %%D in (__pycache__) do if exist "%%D" rmdir /s /q "%%D" 2>nul
    for /d /r "%PROJ_ROOT%" %%D in (*.egg-info) do if exist "%%D" rmdir /s /q "%%D" 2>nul
    call :ui_info "已清理 __pycache__ / *.egg-info"
)
call :ui_ok

REM --- 5. Ollama 模型 ---
if "%WITH_MODEL%"=="1" (
    call :ui_step "删除 Ollama 模型"
    if not defined APM_LLM_MODEL set "APM_LLM_MODEL=qwen2.5:7b-instruct"
    where ollama >nul 2>nul
    if errorlevel 1 (
        call :ui_info "ollama 未安装，跳过"
    ) else (
        if "%DRY_RUN%"=="1" (call :ui_info "[DRY] ollama rm !APM_LLM_MODEL!") else (ollama rm "!APM_LLM_MODEL!" 2>nul & call :ui_info "已移除模型 !APM_LLM_MODEL!")
    )
    call :ui_ok
)

REM --- 6. Ollama 二进制 ---
if "%WITH_OLLAMA%"=="1" (
    call :ui_step "卸载 Ollama 二进制"
    where winget >nul 2>nul
    if errorlevel 1 (
        call :ui_warn "未找到 winget，请手动卸载"
    ) else (
        if "%DRY_RUN%"=="1" (call :ui_info "[DRY] winget uninstall Ollama.Ollama") else (winget uninstall -e --id Ollama.Ollama --accept-source-agreements --silent 2>nul & call :ui_info "已请求卸载 Ollama")
    )
    if exist "%USERPROFILE%\.ollama" (
        if "%DRY_RUN%"=="1" (call :ui_info "[DRY] rmdir /s /q %USERPROFILE%\.ollama") else (rmdir /s /q "%USERPROFILE%\.ollama" 2>nul & call :ui_info "已删除 %USERPROFILE%\.ollama")
    )
    call :ui_ok
)

REM --- 7. Purge ---
if "%PURGE%"=="1" (
    call :ui_step "删除整个项目目录"
    call :ui_info "目标: %PROJ_ROOT%"
    if "%DRY_RUN%"=="1" (
        call :ui_info "[DRY] cd /d %PROJ_ROOT%\.. ^&^& rmdir /s /q %PROJ_ROOT%"
    ) else (
        cd /d "%PROJ_ROOT%\.."
        rmdir /s /q "%PROJ_ROOT%" 2>nul
        call :ui_info "已删除 %PROJ_ROOT%"
    )
    call :ui_ok
)

call :ui_summary
echo.
if "%DRY_RUN%"=="1" (
    echo DRY-RUN 完成；如需真正执行请去掉 /dry-run。
) else (
    echo 卸载完成。如需重新安装：scripts\deploy.bat
)
endlocal
exit /b 0

:_clean_dir
if exist "%PROJ_ROOT%\%~1" (
    if "%DRY_RUN%"=="1" (call :ui_info "[DRY] rmdir /s /q %~1") else (rmdir /s /q "%PROJ_ROOT%\%~1" 2>nul & call :ui_info "已移除 %~1")
)
exit /b 0

:_clean_file
if exist "%PROJ_ROOT%\%~1" (
    if "%DRY_RUN%"=="1" (call :ui_info "[DRY] del %~1") else (del /f /q "%PROJ_ROOT%\%~1" 2>nul & call :ui_info "已移除 %~1")
)
exit /b 0

REM ============================================================
REM  >>>>>>>>>>>>>>>>  _common.bat 内容内联区  <<<<<<<<<<<<<<<<
REM ============================================================

:_common_inlined
REM ============================================================
REM scripts\_common.bat - Windows 安装/部署脚本共享函数库
REM
REM 专业安装器 UI（CMD 版）：
REM   step header N/M plus percent, single-line progress bar, elapsed seconds
REM   :ui_banner / :ui_step / :ui_ok / :ui_warn / :ui_fail / :ui_summary
REM
REM 系统工具：
REM   :refresh_path   - winget 安装后从注册表刷新本进程 PATH
REM   :find_python    - 跳过 Microsoft Store stub，定位真实 python.exe -> PY_EXE
REM
REM 所有全局变量以 _UI_ / _MS_ 开头，避免和调用者冲突。
REM
REM 约定：调用者 setlocal enabledelayedexpansion 后用 "call :ui_step ..." 调用；
REM       调用者通过 set LOG=... 指定日志文件。
REM
REM 本文件由 deploy.bat 直接 `call`。install.bat 由 scripts/build_install.py
REM 在打包时内联此文件的函数段，以满足"单文件一键安装"约束。
REM ============================================================

REM 被 call 时直接跳过函数定义区到 :_common_loaded 标签
goto :_common_loaded

REM ====================== UI: banner ======================
:ui_banner
REM %~1 = title, %~2 = subtitle (optional)
echo.
echo +------------------------------------------------------------+
echo ^|   %~1
if not "%~2"=="" echo ^|   %~2
echo +------------------------------------------------------------+
echo.
exit /b 0

REM ====================== UI: init ======================
:ui_init
REM %~1 = total steps
set "_UI_TOTAL=%~1"
set "_UI_CUR=0"
set "_UI_SUMMARY_FILE=%TEMP%\_ms_summary_%RANDOM%%RANDOM%.txt"
type nul > "%_UI_SUMMARY_FILE%" 2>nul
call :_init_colors
exit /b 0

REM ====================== UI: colors ======================
REM Captures ANSI ESC into _C_ESC and exposes _C_GREEN / _C_RED / _C_YELLOW /
REM _C_CYAN / _C_BOLD / _C_RESET. Win10 1607+ conhost renders them; older or
REM redirected output sees plain text. Set NO_COLOR=1 to disable.
:_init_colors
if defined _C_RESET exit /b 0
set "_C_RESET="
set "_C_GREEN="
set "_C_RED="
set "_C_YELLOW="
set "_C_CYAN="
set "_C_BOLD="
if defined NO_COLOR exit /b 0
REM Persist Virtual-Terminal level so cmd renders ANSI sequences. Idempotent.
reg add "HKCU\Console" /v VirtualTerminalLevel /t REG_DWORD /d 1 /f >nul 2>nul
REM Capture the ESC byte using the well-known prompt-and-rem trick.
REM Output of `prompt #$E#` (after the dummy for body fires it) is "#<ESC>#".
REM `for /f "delims=#"` then strips the surrounding '#' and leaves us with
REM the bare ESC character.
for /f "delims=#" %%E in ('"prompt #$E# & echo on & for %%a in (1) do rem"') do (
    if not defined _C_ESC set "_C_ESC=%%E"
)
if not defined _C_ESC exit /b 0
set "_C_RESET=%_C_ESC%[0m"
set "_C_GREEN=%_C_ESC%[32m"
set "_C_RED=%_C_ESC%[31m"
set "_C_YELLOW=%_C_ESC%[33m"
set "_C_CYAN=%_C_ESC%[36m"
set "_C_BOLD=%_C_ESC%[1m"
exit /b 0

REM ====================== UI: step ======================
:ui_step
REM %~1 = label
set /a _UI_CUR=_UI_CUR+1
set "_UI_CUR_LABEL=%~1"
set /a _UI_PCT=_UI_CUR*100/_UI_TOTAL
set "_UI_T0=%TIME%"
echo.
echo ^>^> [%_UI_CUR%/%_UI_TOTAL%] %~1 ^(%_UI_PCT%%%^)
call :_ui_progress_bar %_UI_PCT%
if defined LOG echo [STEP %TIME%] [%_UI_CUR%/%_UI_TOTAL%] %~1 >> "%LOG%"
exit /b 0

REM ====================== UI: progress bar ======================
:_ui_progress_bar
REM %~1 = pct (0-100)
set /a _UI_BAR_FILLED=%~1*30/100
set /a _UI_BAR_EMPTY=30-_UI_BAR_FILLED
set "_UI_BAR_STR="
for /l %%i in (1,1,%_UI_BAR_FILLED%) do set "_UI_BAR_STR=!_UI_BAR_STR!#"
for /l %%i in (1,1,%_UI_BAR_EMPTY%) do set "_UI_BAR_STR=!_UI_BAR_STR!-"
echo    [!_UI_BAR_STR!] %~1%%
exit /b 0

REM ====================== UI: ok ======================
:ui_ok
REM %~1 = optional note
call :_ui_elapsed
if "%~1"=="" (
    echo    !_C_GREEN![OK]!_C_RESET! done ^(!_UI_ELAPSED!s^)
) else (
    echo    !_C_GREEN![OK]!_C_RESET! %~1 ^(!_UI_ELAPSED!s^)
)
echo OK^|%_UI_CUR_LABEL%^|!_UI_ELAPSED! >> "%_UI_SUMMARY_FILE%"
if defined LOG echo [OK %TIME%] %_UI_CUR_LABEL% took !_UI_ELAPSED!s >> "%LOG%"
exit /b 0

REM ====================== UI: warn ======================
:ui_warn
echo    !_C_YELLOW![!!]!_C_RESET! %~1
if defined LOG echo [WARN %TIME%] %~1 >> "%LOG%"
exit /b 0

REM ====================== UI: ok with warn ======================
:ui_ok_warn
call :_ui_elapsed
echo    !_C_YELLOW![!!]!_C_RESET! %~1 ^(!_UI_ELAPSED!s^)
echo WARN^|%_UI_CUR_LABEL%^|!_UI_ELAPSED! >> "%_UI_SUMMARY_FILE%"
if defined LOG echo [WARN-OK %TIME%] %_UI_CUR_LABEL% took !_UI_ELAPSED!s >> "%LOG%"
exit /b 0

REM ====================== UI: fail ======================
:ui_fail
call :_ui_elapsed
echo    !_C_RED![X]!_C_RESET! %~1 ^(!_UI_ELAPSED!s^)
echo FAIL^|%_UI_CUR_LABEL%^|!_UI_ELAPSED! >> "%_UI_SUMMARY_FILE%"
if defined LOG echo [FAIL %TIME%] %_UI_CUR_LABEL% ^(%~1^) took !_UI_ELAPSED!s >> "%LOG%"
exit /b 0

REM ====================== UI: info ======================
:ui_info
echo    !_C_CYAN![i]!_C_RESET! %~1
if defined LOG echo [INFO %TIME%] %~1 >> "%LOG%"
exit /b 0

REM ====================== UI: summary ======================
:ui_summary
echo.
echo +------------------------------------------------------------+
echo ^|   部署摘要
echo +------------------------------------------------------------+
set "_UI_ANY_FAIL=0"
set "_UI_ANY_WARN=0"
if exist "%_UI_SUMMARY_FILE%" (
    for /f "usebackq tokens=1,2,3 delims=|" %%a in ("%_UI_SUMMARY_FILE%") do (
        if "%%a"=="OK"   echo    !_C_GREEN![OK]!_C_RESET! %%b ^(%%cs^)
        if "%%a"=="WARN" (echo    !_C_YELLOW![!!]!_C_RESET! %%b ^(%%cs^) & set "_UI_ANY_WARN=1")
        if "%%a"=="FAIL" (echo    !_C_RED![X]!_C_RESET!  %%b ^(%%cs^) & set "_UI_ANY_FAIL=1")
    )
    del "%_UI_SUMMARY_FILE%" >nul 2>nul
)
echo.
if "!_UI_ANY_FAIL!"=="1" (
    echo !_C_RED![X]!_C_RESET! 部署存在失败步骤，请查看上方日志
    exit /b 1
)
if "!_UI_ANY_WARN!"=="1" (
    echo !_C_YELLOW![!!]!_C_RESET! 部署完成（有警告）
    exit /b 0
)
echo !_C_GREEN![OK]!_C_RESET! 部署完成，一切就绪
exit /b 0

REM ====================== UI: elapsed helper ======================
:_ui_elapsed
if not defined _UI_T0 (set "_UI_ELAPSED=0" & exit /b 0)
call :_time_to_ms "%_UI_T0%" _UI_T0_MS
call :_time_to_ms "%TIME%"    _UI_T1_MS
set /a _UI_DIFF_MS=_UI_T1_MS-_UI_T0_MS
if !_UI_DIFF_MS! LSS 0 set /a _UI_DIFF_MS+=86400000
set /a _UI_ELAPSED=_UI_DIFF_MS/1000
exit /b 0

REM ====================== time parser: HH:MM:SS.cs -> ms ======================
:_time_to_ms
set "_TS=%~1"
for /f "tokens=1-4 delims=:., " %%a in ("%_TS%") do (
    set /a %~2=^(^(1%%a-100^)*3600 + ^(1%%b-100^)*60 + ^(1%%c-100^)^)*1000 + ^(1%%d-100^)*10
)
exit /b 0

REM ====================== system: PATH refresh from registry ======================
:refresh_path
set "_NEWPATH="
for /f "usebackq tokens=2*" %%A in (`reg query "HKLM\System\CurrentControlSet\Control\Session Manager\Environment" /v Path 2^>nul`) do set "_NEWPATH=%%B"
for /f "usebackq tokens=2*" %%A in (`reg query "HKCU\Environment" /v Path 2^>nul`) do set "_NEWPATH=!_NEWPATH!;%%B"
if defined _NEWPATH (
    set "PATH=!_NEWPATH!"
    if defined LOG echo [PATH-REFRESH %TIME%] done >> "%LOG%"
)
exit /b 0

REM ====================== locate: tools that may not be on PATH after winget ======================
REM Each :locate_<tool> probes well-known install paths AND falls back to a
REM recursive search under WinGet's package storage / Program Files. On
REM success it prepends the directory to PATH. Caller does
REM   call :locate_<tool>
REM   where <tool> >nul 2>nul
REM and decides what to do based on errorlevel.
REM
REM All hits are logged to %LOG% (if defined) so we can diagnose silent
REM mismatches without forcing the user to share their PATH.

:locate_node
where node >nul 2>nul && exit /b 0
if defined LOG echo [LOCATE-NODE %TIME%] starting probe >> "%LOG%"
for %%D in (
    "%ProgramFiles%\nodejs"
    "%ProgramFiles(x86)%\nodejs"
    "%LOCALAPPDATA%\Programs\nodejs"
    "%LOCALAPPDATA%\Microsoft\WinGet\Links"
) do (
    if exist "%%~D\node.exe" (
        if defined LOG echo [LOCATE-NODE]   static hit: %%~D >> "%LOG%"
        set "PATH=%%~D;!PATH!"
    )
)
where node >nul 2>nul && exit /b 0
call :_recursive_locate node.exe
exit /b 0

:locate_git
where git >nul 2>nul && exit /b 0
if defined LOG echo [LOCATE-GIT %TIME%] starting probe >> "%LOG%"
for %%D in (
    "%ProgramFiles%\Git\cmd"
    "%ProgramFiles(x86)%\Git\cmd"
    "%LOCALAPPDATA%\Programs\Git\cmd"
    "%LOCALAPPDATA%\Microsoft\WinGet\Links"
) do (
    if exist "%%~D\git.exe" (
        if defined LOG echo [LOCATE-GIT]   static hit: %%~D >> "%LOG%"
        set "PATH=%%~D;!PATH!"
    )
)
where git >nul 2>nul && exit /b 0
call :_recursive_locate git.exe
exit /b 0

:locate_ollama
where ollama >nul 2>nul && exit /b 0
if defined LOG echo [LOCATE-OLLAMA %TIME%] starting probe >> "%LOG%"
for %%D in (
    "%LOCALAPPDATA%\Programs\Ollama"
    "%ProgramFiles%\Ollama"
    "%LOCALAPPDATA%\Microsoft\WinGet\Links"
) do (
    if exist "%%~D\ollama.exe" (
        if defined LOG echo [LOCATE-OLLAMA]   static hit: %%~D >> "%LOG%"
        set "PATH=%%~D;!PATH!"
    )
)
where ollama >nul 2>nul && exit /b 0
call :_recursive_locate ollama.exe
exit /b 0

REM Best-effort recursive search for an exe under WinGet's storage and
REM Program Files. Slow but bulletproof — only invoked when static probes fail.
:_recursive_locate
set "_LOC_EXE=%~1"
for %%R in (
    "%LOCALAPPDATA%\Microsoft\WinGet\Packages"
    "%ProgramFiles%\WinGet\Packages"
    "%ProgramFiles%"
    "%ProgramFiles(x86)%"
    "%LOCALAPPDATA%\Programs"
) do (
    if exist "%%~R" (
        for /f "delims=" %%F in ('where /R "%%~R" "!_LOC_EXE!" 2^>nul') do (
            if not defined _LOC_HIT (
                set "_LOC_HIT=%%F"
                if defined LOG echo [LOCATE]   recursive hit: %%F >> "%LOG%"
                for %%P in ("%%F") do set "PATH=%%~dpP;!PATH!"
            )
        )
    )
)
set "_LOC_EXE="
set "_LOC_HIT="
exit /b 0

REM ====================== install winget itself ======================
REM Downloads the latest Microsoft.DesktopAppInstaller .msixbundle from
REM GitHub releases and installs via Add-AppxPackage. Used to bootstrap a
REM working winget on machines whose in-box winget is missing or too old
REM (e.g. v1.2 with corrupt source database). Sets WINGET_EXE on success.
REM Requires PowerShell + internet. exit /b 0 on success, 1 on failure.
:install_winget
where powershell >nul 2>nul
if errorlevel 1 (
    if defined LOG echo [INSTALL-WINGET] no powershell available >> "%LOG%"
    exit /b 1
)
set "_WG_TMP=%TEMP%\AppInstaller_%RANDOM%.msixbundle"
if defined LOG echo [INSTALL-WINGET %TIME%] downloading latest msixbundle from GitHub >> "%LOG%"
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$ErrorActionPreference='Stop'; $ProgressPreference='SilentlyContinue'; [Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12; $r = Invoke-RestMethod 'https://api.github.com/repos/microsoft/winget-cli/releases/latest'; $u = ($r.assets | Where-Object { $_.name -like '*.msixbundle' } | Select-Object -First 1).browser_download_url; if (-not $u) { throw 'no msixbundle' }; Invoke-WebRequest -Uri $u -OutFile '%_WG_TMP%'" >> "%LOG%" 2>&1
if not exist "%_WG_TMP%" (
    if defined LOG echo [INSTALL-WINGET] download failed >> "%LOG%"
    exit /b 1
)
if defined LOG echo [INSTALL-WINGET] installing via Add-AppxPackage >> "%LOG%"
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$ErrorActionPreference='Stop'; Add-AppxPackage -Path '%_WG_TMP%' -ForceApplicationShutdown" >> "%LOG%" 2>&1
set "_AP_RC=%ERRORLEVEL%"
del "%_WG_TMP%" >nul 2>nul
if not "%_AP_RC%"=="0" (
    if defined LOG echo [INSTALL-WINGET] Add-AppxPackage rc=%_AP_RC% >> "%LOG%"
    exit /b 1
)
REM Re-detect winget after install
set "WINGET_EXE="
if exist "%LOCALAPPDATA%\Microsoft\WindowsApps\winget.exe" set "WINGET_EXE=%LOCALAPPDATA%\Microsoft\WindowsApps\winget.exe"
if not defined WINGET_EXE (
    for /f "delims=" %%W in ('where winget 2^>nul') do if not defined WINGET_EXE set "WINGET_EXE=%%W"
)
if not defined WINGET_EXE (
    if defined LOG echo [INSTALL-WINGET] post-install detect failed >> "%LOG%"
    exit /b 1
)
if defined LOG echo [INSTALL-WINGET] success: !WINGET_EXE! >> "%LOG%"
exit /b 0

REM ====================== system: find real Python ======================
:find_python
set "PY_EXE="
for /f "delims=" %%P in ('where python 2^>nul') do (
    if not defined PY_EXE (
        call :_is_real_python "%%P" _IS_REAL
        if "!_IS_REAL!"=="1" set "PY_EXE=%%P"
    )
)
if defined PY_EXE exit /b 0
where py >nul 2>nul
if not errorlevel 1 (
    for /f "delims=" %%P in ('py -3 -c "import sys;print(sys.executable)" 2^>nul') do if not defined PY_EXE set "PY_EXE=%%P"
)
if defined PY_EXE exit /b 0
for /d %%D in ("%LOCALAPPDATA%\Programs\Python\Python3*") do (
    if exist "%%D\python.exe" if not defined PY_EXE set "PY_EXE=%%D\python.exe"
)
if defined PY_EXE exit /b 0
REM Last resort: scan WinGet packages and Program Files trees.
if defined LOG echo [LOCATE-PYTHON %TIME%] starting recursive probe >> "%LOG%"
for %%R in (
    "%LOCALAPPDATA%\Microsoft\WinGet\Packages"
    "%ProgramFiles%\Python311"
    "%ProgramFiles%\Python312"
    "%ProgramFiles%\Python313"
) do (
    if exist "%%~R" (
        for /f "delims=" %%F in ('where /R "%%~R" python.exe 2^>nul') do (
            if not defined PY_EXE (
                call :_is_real_python "%%F" _IS_REAL
                if "!_IS_REAL!"=="1" (
                    set "PY_EXE=%%F"
                    if defined LOG echo [LOCATE-PYTHON]   recursive hit: %%F >> "%LOG%"
                )
            )
        )
    )
)
exit /b 0

REM Judge if %~1 is a real Python (vs Microsoft Store 0-byte stub)
:_is_real_python
set "%~2=0"
echo %~1 | findstr /i "WindowsApps" >nul
if not errorlevel 1 (
    for %%F in ("%~1") do if %%~zF LEQ 1024 exit /b 0
)
set "%~2=1"
exit /b 0

REM ============================================================
REM 加载完成标签 —— 被 call 时从 goto :_common_loaded 跳到此处
REM ============================================================
:_common_loaded
exit /b 0
