@echo off
REM  DO NOT EDIT: generated by scripts/build_scripts.py
REM    Sources: scripts/*.tmpl  +  scripts/_common.bat
REM    Regenerate with:  python scripts/build_scripts.py
REM ============================================================
REM scripts/deploy.bat - Windows 首次部署脚本
REM
REM !!! 本文件由 scripts/build_scripts.py 自动生成，请勿手动编辑 !!!
REM !!! 修改源：scripts/deploy.bat.tmpl + scripts/_common.bat   !!!
REM
REM 流程：
REM   1. 后端 venv (backend/.venv) + pip install -e ".[dev]"
REM   2. 前端 npm install + npm run build → frontend/dist
REM   3. Ollama 检查 + ollama pull <model>
REM
REM 日志：
REM   - install.bat 调用时继承 %LOG%
REM   - 独立运行时写到 <项目根>\deploy.log
REM ============================================================

setlocal enabledelayedexpansion
chcp 65001 > nul

set "_SCRIPT_DIR=%~dp0"
if "%_SCRIPT_DIR:~-1%"=="\" set "_SCRIPT_DIR=%_SCRIPT_DIR:~0,-1%"

if exist "%_SCRIPT_DIR%\backend\pyproject.toml" (
    set "PROJ_ROOT=%_SCRIPT_DIR%"
    goto :have_proj_root
)
if exist "%_SCRIPT_DIR%\..\backend\pyproject.toml" (
    for %%I in ("%_SCRIPT_DIR%\..") do set "PROJ_ROOT=%%~fI"
    goto :have_proj_root
)

echo [FATAL] 未找到 backend\pyproject.toml，无法定位项目根
pause & exit /b 1

:have_proj_root
cd /d "%PROJ_ROOT%"

if "%LOG%"=="" (
    set "LOG=%PROJ_ROOT%\deploy.log"
    echo ============================================================ > "!LOG!"
    echo deploy.bat log - %DATE% %TIME% >> "!LOG!"
    echo ============================================================ >> "!LOG!"
    set OWN_LOG=1
) else (
    echo. >> "%LOG%"
    echo ============================================================ >> "%LOG%"
    echo deploy.bat invoked from install.bat - %DATE% %TIME% >> "%LOG%"
    echo ============================================================ >> "%LOG%"
    set OWN_LOG=0
)

call :ui_banner "ai-ppt-maker 首次部署 (Windows)" "venv + pip + npm + Ollama 模型"
call :ui_init 5

set "WINGET_EXE="
if exist "%LOCALAPPDATA%\Microsoft\WindowsApps\winget.exe" set "WINGET_EXE=%LOCALAPPDATA%\Microsoft\WindowsApps\winget.exe"
if not defined WINGET_EXE (
    for /f "delims=" %%W in ('where winget 2^>nul') do if not defined WINGET_EXE set "WINGET_EXE=%%W"
)

REM --- 1. Python ---
call :ui_step "检查 Python (>=3.11)"
call :find_python
if not defined PY_EXE (
    if defined WINGET_EXE (
        call :ui_info "winget install Python.Python.3.11..."
        "!WINGET_EXE!" install -e --id Python.Python.3.11 --accept-package-agreements --accept-source-agreements --silent >> "%LOG%" 2>&1
        call :refresh_path
        call :find_python
    )
)
if not defined PY_EXE (
    call :ui_fail "未找到 Python (3.11+)"
    call :ui_summary
    pause & exit /b 1
)
set "_PYVER_FILE=%TEMP%\_apm_pyver_%RANDOM%.txt"
"!PY_EXE!" --version > "!_PYVER_FILE!" 2>&1
set "_PYLINE="
if exist "!_PYVER_FILE!" (
    set /p _PYLINE=<"!_PYVER_FILE!"
    del "!_PYVER_FILE!" >nul 2>nul
)
set "PYVER="
for /f "tokens=2" %%v in ("!_PYLINE!") do set "PYVER=%%v"
for /f "tokens=1,2 delims=." %%a in ("!PYVER!") do (
    set PYMAJ=%%a
    set PYMIN=%%b
)
if !PYMAJ! LSS 3 (
    call :ui_fail "Python 版本过低，需要 3.11+，当前 !PYVER!"
    call :ui_summary
    pause & exit /b 1
)
if !PYMAJ! EQU 3 if !PYMIN! LSS 11 (
    call :ui_fail "Python 版本过低，需要 3.11+，当前 !PYVER!"
    call :ui_summary
    pause & exit /b 1
)
call :ui_ok "Python !PYVER!"

REM --- 2. backend venv + 依赖 ---
call :ui_step "后端 venv + pip install"
set "VENV_DIR=%PROJ_ROOT%\backend\.venv"
set "VENV_BROKEN=0"
if exist "%VENV_DIR%\Scripts\python.exe" (
    "%VENV_DIR%\Scripts\python.exe" -c "import pip" >> "%LOG%" 2>&1
    if errorlevel 1 set "VENV_BROKEN=1"
)
if "!VENV_BROKEN!"=="1" (
    call :ui_info "检测到损坏的 venv，重建..."
    rmdir /s /q "%VENV_DIR%" >> "%LOG%" 2>&1
)
if not exist "%VENV_DIR%\Scripts\python.exe" (
    "!PY_EXE!" -m venv "%VENV_DIR%" >> "%LOG%" 2>&1
    if errorlevel 1 (
        call :ui_fail "创建 venv 失败，详见 %LOG%"
        call :ui_summary
        pause & exit /b 1
    )
)
set "VENV_PY=%VENV_DIR%\Scripts\python.exe"
call :ui_info "升级 pip..."
"%VENV_PY%" -m pip install --upgrade pip >> "%LOG%" 2>&1
call :ui_info "安装 backend 依赖 (pip install -e .[dev])..."
pushd "%PROJ_ROOT%\backend"
"%VENV_PY%" -m pip install -e ".[dev]" >> "%LOG%" 2>&1
set "PIP_RC=!errorlevel!"
popd
if not "!PIP_RC!"=="0" (
    call :ui_fail "backend pip install 失败，详见 %LOG%"
    call :ui_summary
    pause & exit /b 1
)
call :ui_ok

REM --- 3. Node.js ---
call :ui_step "检查 Node.js (>=18)"
where node >nul 2>nul
if errorlevel 1 (
    if defined WINGET_EXE (
        call :ui_info "winget install OpenJS.NodeJS.LTS..."
        "!WINGET_EXE!" install -e --id OpenJS.NodeJS.LTS --accept-package-agreements --accept-source-agreements --silent >> "%LOG%" 2>&1
        call :refresh_path
    )
)
where node >nul 2>nul
if errorlevel 1 (
    call :ui_fail "未找到 Node.js (18+)"
    call :ui_summary
    pause & exit /b 1
)
for /f "delims=" %%v in ('node --version 2^>^&1') do set NODEVER=%%v
call :ui_ok "Node !NODEVER!"

REM --- 4. 前端 npm install + build ---
call :ui_step "前端 npm install + build"
pushd "%PROJ_ROOT%\frontend"
call :ui_info "npm install ..."
call npm install --no-audit --no-fund >> "%LOG%" 2>&1
if errorlevel 1 (
    popd
    call :ui_fail "npm install 失败，详见 %LOG%"
    call :ui_summary
    pause & exit /b 1
)
call :ui_info "npm run build ..."
call npm run build >> "%LOG%" 2>&1
if errorlevel 1 (
    popd
    call :ui_fail "npm run build 失败，详见 %LOG%"
    call :ui_summary
    pause & exit /b 1
)
popd
call :ui_ok

REM --- 5. Ollama 检查 + 拉模型 ---
call :ui_step "检查 Ollama + 拉取模型"
set "OLLAMA_WARN=0"
where ollama >nul 2>nul
if errorlevel 1 (
    if defined WINGET_EXE (
        call :ui_info "winget install Ollama.Ollama..."
        "!WINGET_EXE!" install -e --id Ollama.Ollama --accept-package-agreements --accept-source-agreements --silent >> "%LOG%" 2>&1
        if errorlevel 1 (
            call :ui_warn "winget 安装 Ollama 失败"
            set "OLLAMA_WARN=1"
            goto :ollama_done
        )
        call :refresh_path
    ) else (
        call :ui_warn "未找到 ollama 且 winget 不可用"
        set "OLLAMA_WARN=1"
        goto :ollama_done
    )
)
where ollama >nul 2>nul
if errorlevel 1 (
    call :ui_warn "Ollama 已安装但 PATH 未生效；重开 cmd 后可用"
    set "OLLAMA_WARN=1"
    goto :ollama_done
)
if not defined APM_AUTO_PULL set APM_AUTO_PULL=1
if not defined APM_LLM_MODEL set APM_LLM_MODEL=qwen2.5:7b-instruct
if "!APM_AUTO_PULL!"=="1" (
    call :ui_info "ollama pull !APM_LLM_MODEL! (约 5GB, 首次 10-30 分钟)"
    ollama pull "!APM_LLM_MODEL!"
    if errorlevel 1 (
        call :ui_warn "ollama pull 失败；稍后手动: ollama pull !APM_LLM_MODEL!"
        set "OLLAMA_WARN=1"
    )
) else (
    call :ui_info "已跳过模型拉取 (APM_AUTO_PULL=0)"
    call :ui_info "稍后手动: ollama pull !APM_LLM_MODEL!"
)
:ollama_done
if "!OLLAMA_WARN!"=="1" (
    call :ui_ok_warn "Ollama 部分完成"
) else (
    call :ui_ok
)

call :ui_summary

echo.
echo 日常启动: 双击 scripts\start.bat
echo 日志文件: %LOG%
if "%OWN_LOG%"=="1" pause
endlocal
exit /b 0

REM ============================================================
REM  >>>>>>>>>>>>>>>>  _common.bat 内容内联区  <<<<<<<<<<<<<<<<
REM ============================================================

:_common_inlined
REM ============================================================
REM scripts\_common.bat - Windows 安装/部署脚本共享函数库
REM
REM 专业安装器 UI（CMD 版）：
REM   step header N/M plus percent, single-line progress bar, elapsed seconds
REM   :ui_banner / :ui_step / :ui_ok / :ui_warn / :ui_fail / :ui_summary
REM
REM 系统工具：
REM   :refresh_path   - winget 安装后从注册表刷新本进程 PATH
REM   :find_python    - 跳过 Microsoft Store stub，定位真实 python.exe -> PY_EXE
REM
REM 所有全局变量以 _UI_ / _MS_ 开头，避免和调用者冲突。
REM
REM 约定：调用者 setlocal enabledelayedexpansion 后用 "call :ui_step ..." 调用；
REM       调用者通过 set LOG=... 指定日志文件。
REM
REM 本文件由 deploy.bat 直接 `call`。install.bat 由 scripts/build_install.py
REM 在打包时内联此文件的函数段，以满足"单文件一键安装"约束。
REM ============================================================

REM 被 call 时直接跳过函数定义区到 :_common_loaded 标签
goto :_common_loaded

REM ====================== UI: banner ======================
:ui_banner
REM %~1 = title, %~2 = subtitle (optional)
echo.
echo +------------------------------------------------------------+
echo ^|   %~1
if not "%~2"=="" echo ^|   %~2
echo +------------------------------------------------------------+
echo.
exit /b 0

REM ====================== UI: init ======================
:ui_init
REM %~1 = total steps
set "_UI_TOTAL=%~1"
set "_UI_CUR=0"
set "_UI_SUMMARY_FILE=%TEMP%\_ms_summary_%RANDOM%%RANDOM%.txt"
type nul > "%_UI_SUMMARY_FILE%" 2>nul
call :_init_colors
exit /b 0

REM ====================== UI: colors ======================
REM Captures ANSI ESC into _C_ESC and exposes _C_GREEN / _C_RED / _C_YELLOW /
REM _C_CYAN / _C_BOLD / _C_RESET. Win10 1607+ conhost renders them; older or
REM redirected output sees plain text. Set NO_COLOR=1 to disable.
:_init_colors
if defined _C_RESET exit /b 0
set "_C_RESET="
set "_C_GREEN="
set "_C_RED="
set "_C_YELLOW="
set "_C_CYAN="
set "_C_BOLD="
if defined NO_COLOR exit /b 0
REM Persist Virtual-Terminal level so cmd renders ANSI sequences. Idempotent.
reg add "HKCU\Console" /v VirtualTerminalLevel /t REG_DWORD /d 1 /f >nul 2>nul
REM Capture the ESC byte using the well-known prompt-and-rem trick.
REM Output of `prompt #$E#` (after the dummy for body fires it) is "#<ESC>#".
REM `for /f "delims=#"` then strips the surrounding '#' and leaves us with
REM the bare ESC character.
for /f "delims=#" %%E in ('"prompt #$E# & echo on & for %%a in (1) do rem"') do (
    if not defined _C_ESC set "_C_ESC=%%E"
)
if not defined _C_ESC exit /b 0
set "_C_RESET=%_C_ESC%[0m"
set "_C_GREEN=%_C_ESC%[32m"
set "_C_RED=%_C_ESC%[31m"
set "_C_YELLOW=%_C_ESC%[33m"
set "_C_CYAN=%_C_ESC%[36m"
set "_C_BOLD=%_C_ESC%[1m"
exit /b 0

REM ====================== UI: step ======================
:ui_step
REM %~1 = label
set /a _UI_CUR=_UI_CUR+1
set "_UI_CUR_LABEL=%~1"
set /a _UI_PCT=_UI_CUR*100/_UI_TOTAL
set "_UI_T0=%TIME%"
echo.
echo ^>^> [%_UI_CUR%/%_UI_TOTAL%] %~1 ^(%_UI_PCT%%%^)
call :_ui_progress_bar %_UI_PCT%
if defined LOG echo [STEP %TIME%] [%_UI_CUR%/%_UI_TOTAL%] %~1 >> "%LOG%"
exit /b 0

REM ====================== UI: progress bar ======================
:_ui_progress_bar
REM %~1 = pct (0-100)
set /a _UI_BAR_FILLED=%~1*30/100
set /a _UI_BAR_EMPTY=30-_UI_BAR_FILLED
set "_UI_BAR_STR="
for /l %%i in (1,1,%_UI_BAR_FILLED%) do set "_UI_BAR_STR=!_UI_BAR_STR!#"
for /l %%i in (1,1,%_UI_BAR_EMPTY%) do set "_UI_BAR_STR=!_UI_BAR_STR!-"
echo    [!_UI_BAR_STR!] %~1%%
exit /b 0

REM ====================== UI: ok ======================
:ui_ok
REM %~1 = optional note
call :_ui_elapsed
if "%~1"=="" (
    echo    !_C_GREEN![OK]!_C_RESET! done ^(!_UI_ELAPSED!s^)
) else (
    echo    !_C_GREEN![OK]!_C_RESET! %~1 ^(!_UI_ELAPSED!s^)
)
echo OK^|%_UI_CUR_LABEL%^|!_UI_ELAPSED! >> "%_UI_SUMMARY_FILE%"
if defined LOG echo [OK %TIME%] %_UI_CUR_LABEL% took !_UI_ELAPSED!s >> "%LOG%"
exit /b 0

REM ====================== UI: warn ======================
:ui_warn
echo    !_C_YELLOW![!!]!_C_RESET! %~1
if defined LOG echo [WARN %TIME%] %~1 >> "%LOG%"
exit /b 0

REM ====================== UI: ok with warn ======================
:ui_ok_warn
call :_ui_elapsed
echo    !_C_YELLOW![!!]!_C_RESET! %~1 ^(!_UI_ELAPSED!s^)
echo WARN^|%_UI_CUR_LABEL%^|!_UI_ELAPSED! >> "%_UI_SUMMARY_FILE%"
if defined LOG echo [WARN-OK %TIME%] %_UI_CUR_LABEL% took !_UI_ELAPSED!s >> "%LOG%"
exit /b 0

REM ====================== UI: fail ======================
:ui_fail
call :_ui_elapsed
echo    !_C_RED![X]!_C_RESET! %~1 ^(!_UI_ELAPSED!s^)
echo FAIL^|%_UI_CUR_LABEL%^|!_UI_ELAPSED! >> "%_UI_SUMMARY_FILE%"
if defined LOG echo [FAIL %TIME%] %_UI_CUR_LABEL% ^(%~1^) took !_UI_ELAPSED!s >> "%LOG%"
exit /b 0

REM ====================== UI: info ======================
:ui_info
echo    !_C_CYAN![i]!_C_RESET! %~1
if defined LOG echo [INFO %TIME%] %~1 >> "%LOG%"
exit /b 0

REM ====================== UI: summary ======================
:ui_summary
echo.
echo +------------------------------------------------------------+
echo ^|   部署摘要
echo +------------------------------------------------------------+
set "_UI_ANY_FAIL=0"
set "_UI_ANY_WARN=0"
if exist "%_UI_SUMMARY_FILE%" (
    for /f "usebackq tokens=1,2,3 delims=|" %%a in ("%_UI_SUMMARY_FILE%") do (
        if "%%a"=="OK"   echo    !_C_GREEN![OK]!_C_RESET! %%b ^(%%cs^)
        if "%%a"=="WARN" (echo    !_C_YELLOW![!!]!_C_RESET! %%b ^(%%cs^) & set "_UI_ANY_WARN=1")
        if "%%a"=="FAIL" (echo    !_C_RED![X]!_C_RESET!  %%b ^(%%cs^) & set "_UI_ANY_FAIL=1")
    )
    del "%_UI_SUMMARY_FILE%" >nul 2>nul
)
echo.
if "!_UI_ANY_FAIL!"=="1" (
    echo !_C_RED![X]!_C_RESET! 部署存在失败步骤，请查看上方日志
    exit /b 1
)
if "!_UI_ANY_WARN!"=="1" (
    echo !_C_YELLOW![!!]!_C_RESET! 部署完成（有警告）
    exit /b 0
)
echo !_C_GREEN![OK]!_C_RESET! 部署完成，一切就绪
exit /b 0

REM ====================== UI: elapsed helper ======================
:_ui_elapsed
if not defined _UI_T0 (set "_UI_ELAPSED=0" & exit /b 0)
call :_time_to_ms "%_UI_T0%" _UI_T0_MS
call :_time_to_ms "%TIME%"    _UI_T1_MS
set /a _UI_DIFF_MS=_UI_T1_MS-_UI_T0_MS
if !_UI_DIFF_MS! LSS 0 set /a _UI_DIFF_MS+=86400000
set /a _UI_ELAPSED=_UI_DIFF_MS/1000
exit /b 0

REM ====================== time parser: HH:MM:SS.cs -> ms ======================
:_time_to_ms
set "_TS=%~1"
for /f "tokens=1-4 delims=:., " %%a in ("%_TS%") do (
    set /a %~2=^(^(1%%a-100^)*3600 + ^(1%%b-100^)*60 + ^(1%%c-100^)^)*1000 + ^(1%%d-100^)*10
)
exit /b 0

REM ====================== system: PATH refresh from registry ======================
:refresh_path
set "_NEWPATH="
for /f "usebackq tokens=2*" %%A in (`reg query "HKLM\System\CurrentControlSet\Control\Session Manager\Environment" /v Path 2^>nul`) do set "_NEWPATH=%%B"
for /f "usebackq tokens=2*" %%A in (`reg query "HKCU\Environment" /v Path 2^>nul`) do set "_NEWPATH=!_NEWPATH!;%%B"
if defined _NEWPATH (
    set "PATH=!_NEWPATH!"
    if defined LOG echo [PATH-REFRESH %TIME%] done >> "%LOG%"
)
exit /b 0

REM ====================== locate: tools that may not be on PATH after winget ======================
REM Each :locate_<tool> probes well-known install paths AND falls back to a
REM recursive search under WinGet's package storage / Program Files. On
REM success it prepends the directory to PATH. Caller does
REM   call :locate_<tool>
REM   where <tool> >nul 2>nul
REM and decides what to do based on errorlevel.
REM
REM All hits are logged to %LOG% (if defined) so we can diagnose silent
REM mismatches without forcing the user to share their PATH.

:locate_node
where node >nul 2>nul && exit /b 0
if defined LOG echo [LOCATE-NODE %TIME%] starting probe >> "%LOG%"
for %%D in (
    "%ProgramFiles%\nodejs"
    "%ProgramFiles(x86)%\nodejs"
    "%LOCALAPPDATA%\Programs\nodejs"
    "%LOCALAPPDATA%\Microsoft\WinGet\Links"
) do (
    if exist "%%~D\node.exe" (
        if defined LOG echo [LOCATE-NODE]   static hit: %%~D >> "%LOG%"
        set "PATH=%%~D;!PATH!"
    )
)
where node >nul 2>nul && exit /b 0
call :_recursive_locate node.exe
exit /b 0

:locate_git
where git >nul 2>nul && exit /b 0
if defined LOG echo [LOCATE-GIT %TIME%] starting probe >> "%LOG%"
for %%D in (
    "%ProgramFiles%\Git\cmd"
    "%ProgramFiles(x86)%\Git\cmd"
    "%LOCALAPPDATA%\Programs\Git\cmd"
    "%LOCALAPPDATA%\Microsoft\WinGet\Links"
) do (
    if exist "%%~D\git.exe" (
        if defined LOG echo [LOCATE-GIT]   static hit: %%~D >> "%LOG%"
        set "PATH=%%~D;!PATH!"
    )
)
where git >nul 2>nul && exit /b 0
call :_recursive_locate git.exe
exit /b 0

:locate_ollama
where ollama >nul 2>nul && exit /b 0
if defined LOG echo [LOCATE-OLLAMA %TIME%] starting probe >> "%LOG%"
for %%D in (
    "%LOCALAPPDATA%\Programs\Ollama"
    "%ProgramFiles%\Ollama"
    "%LOCALAPPDATA%\Microsoft\WinGet\Links"
) do (
    if exist "%%~D\ollama.exe" (
        if defined LOG echo [LOCATE-OLLAMA]   static hit: %%~D >> "%LOG%"
        set "PATH=%%~D;!PATH!"
    )
)
where ollama >nul 2>nul && exit /b 0
call :_recursive_locate ollama.exe
exit /b 0

REM Best-effort recursive search for an exe under WinGet's storage and
REM Program Files. Slow but bulletproof — only invoked when static probes fail.
:_recursive_locate
set "_LOC_EXE=%~1"
for %%R in (
    "%LOCALAPPDATA%\Microsoft\WinGet\Packages"
    "%ProgramFiles%\WinGet\Packages"
    "%ProgramFiles%"
    "%ProgramFiles(x86)%"
    "%LOCALAPPDATA%\Programs"
) do (
    if exist "%%~R" (
        for /f "delims=" %%F in ('where /R "%%~R" "!_LOC_EXE!" 2^>nul') do (
            if not defined _LOC_HIT (
                set "_LOC_HIT=%%F"
                if defined LOG echo [LOCATE]   recursive hit: %%F >> "%LOG%"
                for %%P in ("%%F") do set "PATH=%%~dpP;!PATH!"
            )
        )
    )
)
set "_LOC_EXE="
set "_LOC_HIT="
exit /b 0

REM ====================== install winget itself ======================
REM Downloads the latest Microsoft.DesktopAppInstaller .msixbundle from
REM GitHub releases and installs via Add-AppxPackage. Used to bootstrap a
REM working winget on machines whose in-box winget is missing or too old
REM (e.g. v1.2 with corrupt source database). Sets WINGET_EXE on success.
REM Requires PowerShell + internet. exit /b 0 on success, 1 on failure.
:install_winget
where powershell >nul 2>nul
if errorlevel 1 (
    if defined LOG echo [INSTALL-WINGET] no powershell available >> "%LOG%"
    exit /b 1
)
set "_WG_TMP=%TEMP%\AppInstaller_%RANDOM%.msixbundle"
set "_WG_URL_FILE=%TEMP%\winget_url_%RANDOM%.txt"
if defined LOG echo [INSTALL-WINGET %TIME%] querying GitHub for latest release URL >> "%LOG%"
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$ErrorActionPreference='Stop'; $ProgressPreference='SilentlyContinue'; [Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12; $r = Invoke-RestMethod 'https://api.github.com/repos/microsoft/winget-cli/releases/latest'; $u = ($r.assets | Where-Object { $_.name -like '*.msixbundle' } | Select-Object -First 1).browser_download_url; if (-not $u) { throw 'no msixbundle' }; Set-Content -Path '%_WG_URL_FILE%' -Value $u -NoNewline" 2>> "%LOG%"
if not exist "%_WG_URL_FILE%" (
    if defined LOG echo [INSTALL-WINGET] URL fetch failed >> "%LOG%"
    exit /b 1
)
set "_WG_URL="
set /p _WG_URL=<"%_WG_URL_FILE%"
del "%_WG_URL_FILE%" >nul 2>nul
if not defined _WG_URL (
    if defined LOG echo [INSTALL-WINGET] empty URL >> "%LOG%"
    exit /b 1
)
if defined LOG echo [INSTALL-WINGET] URL=!_WG_URL! >> "%LOG%"
REM Download with visible progress. Prefer curl.exe (Win10 1803+, has built-in
REM progress bar). Fall back to BITS / Invoke-WebRequest in PowerShell.
set "_WG_DL_OK=0"
where curl.exe >nul 2>nul
if not errorlevel 1 (
    echo     ^>^> downloading via curl ^(showing progress^) ...
    curl.exe -L --progress-bar -o "%_WG_TMP%" "!_WG_URL!"
    if exist "%_WG_TMP%" set "_WG_DL_OK=1"
)
if "!_WG_DL_OK!"=="0" (
    echo     ^>^> downloading via PowerShell BITS ^(showing progress^) ...
    powershell -NoProfile -ExecutionPolicy Bypass -Command ^
      "$ErrorActionPreference='Stop'; [Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12; try { Import-Module BitsTransfer -ErrorAction Stop; Start-BitsTransfer -Source '!_WG_URL!' -Destination '%_WG_TMP%' -Description 'winget' } catch { Write-Host 'BITS unavailable, using Invoke-WebRequest'; Invoke-WebRequest -Uri '!_WG_URL!' -OutFile '%_WG_TMP%' }"
    if exist "%_WG_TMP%" set "_WG_DL_OK=1"
)
if "!_WG_DL_OK!"=="0" (
    if defined LOG echo [INSTALL-WINGET] download failed >> "%LOG%"
    exit /b 1
)
if defined LOG for %%S in ("%_WG_TMP%") do echo [INSTALL-WINGET] downloaded %%~zS bytes >> "%LOG%"
echo     ^>^> installing via Add-AppxPackage ...
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$ErrorActionPreference='Stop'; Add-AppxPackage -Path '%_WG_TMP%' -ForceApplicationShutdown" >> "%LOG%" 2>&1
set "_AP_RC=%ERRORLEVEL%"
del "%_WG_TMP%" >nul 2>nul
if not "%_AP_RC%"=="0" (
    if defined LOG echo [INSTALL-WINGET] Add-AppxPackage rc=%_AP_RC% >> "%LOG%"
    exit /b 1
)
REM Re-detect winget after install
set "WINGET_EXE="
if exist "%LOCALAPPDATA%\Microsoft\WindowsApps\winget.exe" set "WINGET_EXE=%LOCALAPPDATA%\Microsoft\WindowsApps\winget.exe"
if not defined WINGET_EXE (
    for /f "delims=" %%W in ('where winget 2^>nul') do if not defined WINGET_EXE set "WINGET_EXE=%%W"
)
if not defined WINGET_EXE (
    if defined LOG echo [INSTALL-WINGET] post-install detect failed >> "%LOG%"
    exit /b 1
)
if defined LOG echo [INSTALL-WINGET] success: !WINGET_EXE! >> "%LOG%"
exit /b 0

REM ====================== system: find real Python ======================
:find_python
set "PY_EXE="
for /f "delims=" %%P in ('where python 2^>nul') do (
    if not defined PY_EXE (
        call :_is_real_python "%%P" _IS_REAL
        if "!_IS_REAL!"=="1" set "PY_EXE=%%P"
    )
)
if defined PY_EXE exit /b 0
where py >nul 2>nul
if not errorlevel 1 (
    for /f "delims=" %%P in ('py -3 -c "import sys;print(sys.executable)" 2^>nul') do if not defined PY_EXE set "PY_EXE=%%P"
)
if defined PY_EXE exit /b 0
for /d %%D in ("%LOCALAPPDATA%\Programs\Python\Python3*") do (
    if exist "%%D\python.exe" if not defined PY_EXE set "PY_EXE=%%D\python.exe"
)
if defined PY_EXE exit /b 0
REM Last resort: scan WinGet packages and Program Files trees.
if defined LOG echo [LOCATE-PYTHON %TIME%] starting recursive probe >> "%LOG%"
for %%R in (
    "%LOCALAPPDATA%\Microsoft\WinGet\Packages"
    "%ProgramFiles%\Python311"
    "%ProgramFiles%\Python312"
    "%ProgramFiles%\Python313"
) do (
    if exist "%%~R" (
        for /f "delims=" %%F in ('where /R "%%~R" python.exe 2^>nul') do (
            if not defined PY_EXE (
                call :_is_real_python "%%F" _IS_REAL
                if "!_IS_REAL!"=="1" (
                    set "PY_EXE=%%F"
                    if defined LOG echo [LOCATE-PYTHON]   recursive hit: %%F >> "%LOG%"
                )
            )
        )
    )
)
exit /b 0

REM Judge if %~1 is a real Python (vs Microsoft Store 0-byte stub)
:_is_real_python
set "%~2=0"
echo %~1 | findstr /i "WindowsApps" >nul
if not errorlevel 1 (
    for %%F in ("%~1") do if %%~zF LEQ 1024 exit /b 0
)
set "%~2=1"
exit /b 0

REM ============================================================
REM 加载完成标签 —— 被 call 时从 goto :_common_loaded 跳到此处
REM ============================================================
:_common_loaded
exit /b 0
