@echo off
REM  DO NOT EDIT: generated by scripts/build_scripts.py
REM    Sources: scripts/*.tmpl  +  scripts/_common.bat
REM    Regenerate with:  python scripts/build_scripts.py
REM ============================================================
REM install.bat - 零基础一键安装入口（Windows 10/11）
REM
REM !!! 本文件由 scripts/build_scripts.py 自动生成，请勿手动编辑 !!!
REM !!! 修改源：scripts/install.bat.tmpl + scripts/_common.bat  !!!
REM
REM 流程：winget 装 Python/Node/Git/Ollama → clone/定位源码 → 调 deploy.bat
REM 所有外部命令的完整输出会追加到 install.log；出错请把 install.log 发给维护者。
REM ============================================================

setlocal enabledelayedexpansion
chcp 65001 > nul
title ai-ppt-maker - 一键安装

set LOG=%~dp0install.log

REM --- 初始化日志 ---
echo ============================================================ > "%LOG%"
echo install.bat log - %DATE% %TIME% >> "%LOG%"
echo CWD: %CD% >> "%LOG%"
echo SCRIPT: %~f0 >> "%LOG%"
echo ============================================================ >> "%LOG%"
ver >> "%LOG%" 2>&1
echo. >> "%LOG%"

call :ui_banner "ai-ppt-maker - 一键安装" "Python + Node + Ollama 模型；首次预计 20-40 分钟"
call :ui_init 6

REM --- 0. winget ---
call :ui_step "检查 winget"
set "WINGET_EXE="
if exist "%LOCALAPPDATA%\Microsoft\WindowsApps\winget.exe" set "WINGET_EXE=%LOCALAPPDATA%\Microsoft\WindowsApps\winget.exe"
if not defined WINGET_EXE (
    for /f "delims=" %%W in ('where winget 2^>nul') do if not defined WINGET_EXE set "WINGET_EXE=%%W"
)
set HAVE_WINGET=0
if defined WINGET_EXE set HAVE_WINGET=1

if %HAVE_WINGET%==1 (
    REM Detect old winget (v1.0..v1.4) — known to have broken source DBs.
    set "_WG_VER="
    for /f "tokens=*" %%V in ('"%WINGET_EXE%" --version 2^>nul') do set "_WG_VER=%%V"
    if defined LOG echo [WINGET-VER] !_WG_VER! >> "%LOG%"
    set "_WG_OLD=0"
    if defined _WG_VER (
        echo !_WG_VER! | findstr /b /c:"v1.0" /c:"v1.1" /c:"v1.2" /c:"v1.3" /c:"v1.4" >nul && set "_WG_OLD=1"
    )
    if "!_WG_OLD!"=="1" (
        call :ui_info "winget 版本过旧 (!_WG_VER!)，自动升级中（下载约 30-100 MB）..."
        call :install_winget
        if not errorlevel 1 (
            for /f "tokens=*" %%V in ('"!WINGET_EXE!" --version 2^>nul') do set "_WG_VER=%%V"
            call :ui_info "winget 已升级到 !_WG_VER!"
        ) else (
            call :ui_warn "winget 自动升级失败（详见 install.log），将继续使用旧版"
        )
    )
    call :ui_ok "winget !_WG_VER!"
) else (
    call :ui_info "winget 不存在，自动安装（下载约 30-100 MB）..."
    call :install_winget
    if not errorlevel 1 (
        set HAVE_WINGET=1
        for /f "tokens=*" %%V in ('"!WINGET_EXE!" --version 2^>nul') do set "_WG_VER=%%V"
        call :ui_ok "winget !_WG_VER! 安装成功"
    ) else (
        call :ui_warn "winget 自动安装失败。请到 Microsoft Store 搜「应用安装程序」装上后重跑"
        call :ui_ok_warn "winget 缺失（继续，但需要手动安装依赖）"
    )
)

REM --- 1. Python ---
call :ui_step "检查 Python"
call :find_python
if not defined PY_EXE (
    if %HAVE_WINGET%==1 (
        call :ui_info "winget install Python.Python.3.11（若弹出 UAC 请允许）..."
        "%WINGET_EXE%" install -e --id Python.Python.3.11 --accept-package-agreements --accept-source-agreements --silent >> "%LOG%" 2>&1
        call :refresh_path
        call :find_python
        if not defined PY_EXE (
            call :ui_info "winget 首次未生效，重置 winget 源后重试 ..."
            "%WINGET_EXE%" source reset --force >> "%LOG%" 2>&1
            "%WINGET_EXE%" source update >> "%LOG%" 2>&1
            "%WINGET_EXE%" install -e --id Python.Python.3.11 --accept-package-agreements --accept-source-agreements --silent >> "%LOG%" 2>&1
            call :refresh_path
            call :find_python
        )
        if not defined PY_EXE (
            call :ui_fail "winget 无法安装 Python（疑似源损坏）。请手动从 https://www.python.org/downloads/ 安装 Python 3.11+ 后重跑本脚本"
            call :ui_summary
            pause & exit /b 1
        )
    ) else (
        call :ui_fail "未找到 Python 且 winget 不可用"
        call :ui_summary
        pause & exit /b 1
    )
)
for /f "tokens=2" %%v in ('"!PY_EXE!" --version 2^>^&1') do set PYVER=%%v
call :ui_ok "Python !PYVER!"

REM --- 2. Node.js ---
call :ui_step "检查 Node.js (>=18)"
where node >nul 2>nul
if errorlevel 1 (
    if %HAVE_WINGET%==1 (
        call :ui_info "winget install OpenJS.NodeJS.LTS ..."
        "%WINGET_EXE%" install -e --id OpenJS.NodeJS.LTS --accept-package-agreements --accept-source-agreements --silent >> "%LOG%" 2>&1
        call :refresh_path
        call :locate_node
        where node >nul 2>nul
        if errorlevel 1 (
            REM winget can return 0 while having silently failed due to source
            REM corruption (e.g. error 0x8a15000f). Reset the source and retry.
            call :ui_info "winget 首次未生效，重置 winget 源后重试 ..."
            "%WINGET_EXE%" source reset --force >> "%LOG%" 2>&1
            "%WINGET_EXE%" source update >> "%LOG%" 2>&1
            "%WINGET_EXE%" install -e --id OpenJS.NodeJS.LTS --accept-package-agreements --accept-source-agreements --silent >> "%LOG%" 2>&1
            call :refresh_path
            call :locate_node
            where node >nul 2>nul
        )
        if errorlevel 1 (
            call :ui_fail "winget 无法安装 Node.js（疑似源损坏）。请手动从 https://nodejs.org 下载 LTS 版安装后重跑本脚本"
            call :ui_summary
            pause & exit /b 1
        )
    ) else (
        call :ui_fail "未找到 Node.js 且 winget 不可用，请从 https://nodejs.org 安装"
        call :ui_summary
        pause & exit /b 1
    )
)
for /f "delims=" %%v in ('node --version 2^>^&1') do set NODEVER=%%v
call :ui_ok "Node !NODEVER!"

REM --- 3. Git ---
call :ui_step "检查 Git"
where git >nul 2>nul
if errorlevel 1 (
    if %HAVE_WINGET%==1 (
        call :ui_info "winget install Git.Git ..."
        "%WINGET_EXE%" install -e --id Git.Git --accept-package-agreements --accept-source-agreements --silent >> "%LOG%" 2>&1
        if errorlevel 1 (
            call :ui_ok_warn "winget 安装 Git 失败（如源码已在本地可忽略）"
        ) else (
            call :refresh_path
            call :locate_git
            where git >nul 2>nul
            if errorlevel 1 (
                call :ui_ok_warn "Git 已安装但当前窗口找不到（试过静态路径与递归）"
            ) else (
                call :ui_ok
            )
        )
    ) else (
        call :ui_ok_warn "未找到 Git 且 winget 不可用，将跳过自动 clone"
    )
) else (
    git --version >> "%LOG%" 2>&1
    call :ui_ok
)

REM --- 4. Ollama ---
call :ui_step "检查 Ollama"
where ollama >nul 2>nul
if errorlevel 1 (
    if %HAVE_WINGET%==1 (
        call :ui_info "winget install Ollama.Ollama ..."
        "%WINGET_EXE%" install -e --id Ollama.Ollama --accept-package-agreements --accept-source-agreements --silent >> "%LOG%" 2>&1
        if errorlevel 1 (
            call :ui_ok_warn "winget 安装 Ollama 失败（M2 后才需要 LLM）"
        ) else (
            call :refresh_path
            call :locate_ollama
            where ollama >nul 2>nul
            if errorlevel 1 (
                call :ui_ok_warn "Ollama 已安装但当前窗口找不到（试过静态路径与递归）"
            ) else (
                call :ui_ok
            )
        )
    ) else (
        call :ui_ok_warn "未找到 Ollama 且 winget 不可用"
    )
) else (
    ollama --version >> "%LOG%" 2>&1
    call :ui_ok
)

REM --- 5. 获取/定位源码 ---
REM     install.bat 现住在 scripts\ 下，所以两种合法位置都要支持：
REM       1) %~dp0           = ...\repo\scripts\   →  PROJ_DIR = %~dp0..
REM       2) %~dp0           = ...\repo\           →  PROJ_DIR = %~dp0
REM          （用户把 install.bat 单独下到任意空目录的旧用法）
call :ui_step "准备项目源码"
set PROJ_DIR=
if exist "%~dp0..\backend\pyproject.toml" (
    REM scripts\install.bat 模式：父目录就是项目根
    pushd "%~dp0.."
    set PROJ_DIR=!CD!
    popd
    call :ui_info "scripts/ 模式，项目根: !PROJ_DIR!"
) else if exist "%~dp0backend\pyproject.toml" (
    set PROJ_DIR=%~dp0
    if "!PROJ_DIR:~-1!"=="\" set PROJ_DIR=!PROJ_DIR:~0,-1!
    call :ui_info "脚本同目录即项目根: !PROJ_DIR!"
) else (
    if defined APM_INSTALL_DIR (
        set PROJ_DIR=!APM_INSTALL_DIR!
    ) else (
        set PROJ_DIR=%USERPROFILE%\ai-ppt-maker
    )
    call :ui_info "安装目录: !PROJ_DIR!  (可用 APM_INSTALL_DIR 覆盖)"

    if exist "!PROJ_DIR!\backend\pyproject.toml" (
        call :ui_info "目录已有项目，执行 git pull ..."
        pushd "!PROJ_DIR!"
        git pull >> "%LOG%" 2>&1
        popd
    ) else (
        where git >nul 2>nul
        if errorlevel 1 (
            call :ui_fail "没有 git 且目标目录无源码，无法继续"
            call :ui_summary
            pause & exit /b 1
        )
        call :ui_info "git clone 到 !PROJ_DIR! ..."
        for %%D in ("!PROJ_DIR!") do if not exist "%%~dpD" md "%%~dpD"
        if not defined APM_REPO_URL set "APM_REPO_URL=https://example.com/REPLACE_ME/ai-ppt-maker.git"
        git clone "!APM_REPO_URL!" "!PROJ_DIR!" >> "%LOG%" 2>&1
        if errorlevel 1 (
            call :ui_fail "git clone 失败，详见 %LOG%（请设置 APM_REPO_URL 指向你的远端仓库）"
            call :ui_summary
            pause & exit /b 1
        )
    )
)
call :ui_ok

REM --- 6. 调用 deploy.bat ---
call :ui_step "部署 venv + 依赖 + 前端 + 拉模型"
cd /d "!PROJ_DIR!"
if not exist "scripts\deploy.bat" (
    call :ui_fail "找不到 scripts\deploy.bat，项目结构异常"
    call :ui_summary
    pause & exit /b 1
)
call "scripts\deploy.bat"
if errorlevel 1 (
    call :ui_fail "deploy.bat 执行失败，详见屏幕与 %LOG%"
    call :ui_summary
    pause & exit /b 1
)
call :ui_ok "deploy.bat 完成"

call :ui_summary

echo.
echo 项目位置: !PROJ_DIR!
echo 日常启动: 双击 !PROJ_DIR!\scripts\start.bat
echo 安装日志: %LOG%
echo.

if not defined APM_AUTO_START set APM_AUTO_START=1
if "!APM_AUTO_START!"=="1" (
    echo [i] 自动启动中...（设环境变量 APM_AUTO_START=0 可禁用）
    start "" "!PROJ_DIR!\scripts\start.bat"
) else (
    echo [i] 已跳过自动启动 (APM_AUTO_START=0)
)
pause
endlocal
exit /b 0

REM ============================================================
REM  >>>>>>>>>>>>>>>>  _common.bat 内容内联区  <<<<<<<<<<<<<<<<
REM ============================================================

:_common_inlined
REM ============================================================
REM scripts\_common.bat - Windows 安装/部署脚本共享函数库
REM
REM 专业安装器 UI（CMD 版）：
REM   step header N/M plus percent, single-line progress bar, elapsed seconds
REM   :ui_banner / :ui_step / :ui_ok / :ui_warn / :ui_fail / :ui_summary
REM
REM 系统工具：
REM   :refresh_path   - winget 安装后从注册表刷新本进程 PATH
REM   :find_python    - 跳过 Microsoft Store stub，定位真实 python.exe -> PY_EXE
REM
REM 所有全局变量以 _UI_ / _MS_ 开头，避免和调用者冲突。
REM
REM 约定：调用者 setlocal enabledelayedexpansion 后用 "call :ui_step ..." 调用；
REM       调用者通过 set LOG=... 指定日志文件。
REM
REM 本文件由 deploy.bat 直接 `call`。install.bat 由 scripts/build_install.py
REM 在打包时内联此文件的函数段，以满足"单文件一键安装"约束。
REM ============================================================

REM 被 call 时直接跳过函数定义区到 :_common_loaded 标签
goto :_common_loaded

REM ====================== UI: banner ======================
:ui_banner
REM %~1 = title, %~2 = subtitle (optional)
echo.
echo +------------------------------------------------------------+
echo ^|   %~1
if not "%~2"=="" echo ^|   %~2
echo +------------------------------------------------------------+
echo.
exit /b 0

REM ====================== UI: init ======================
:ui_init
REM %~1 = total steps
set "_UI_TOTAL=%~1"
set "_UI_CUR=0"
set "_UI_SUMMARY_FILE=%TEMP%\_ms_summary_%RANDOM%%RANDOM%.txt"
type nul > "%_UI_SUMMARY_FILE%" 2>nul
call :_init_colors
exit /b 0

REM ====================== UI: colors ======================
REM Captures ANSI ESC into _C_ESC and exposes _C_GREEN / _C_RED / _C_YELLOW /
REM _C_CYAN / _C_BOLD / _C_RESET. Win10 1607+ conhost renders them; older or
REM redirected output sees plain text. Set NO_COLOR=1 to disable.
:_init_colors
if defined _C_RESET exit /b 0
set "_C_RESET="
set "_C_GREEN="
set "_C_RED="
set "_C_YELLOW="
set "_C_CYAN="
set "_C_BOLD="
if defined NO_COLOR exit /b 0
REM Persist Virtual-Terminal level so cmd renders ANSI sequences. Idempotent.
reg add "HKCU\Console" /v VirtualTerminalLevel /t REG_DWORD /d 1 /f >nul 2>nul
REM Capture the ESC byte using the well-known prompt-and-rem trick.
REM Output of `prompt #$E#` (after the dummy for body fires it) is "#<ESC>#".
REM `for /f "delims=#"` then strips the surrounding '#' and leaves us with
REM the bare ESC character.
for /f "delims=#" %%E in ('"prompt #$E# & echo on & for %%a in (1) do rem"') do (
    if not defined _C_ESC set "_C_ESC=%%E"
)
if not defined _C_ESC exit /b 0
set "_C_RESET=%_C_ESC%[0m"
set "_C_GREEN=%_C_ESC%[32m"
set "_C_RED=%_C_ESC%[31m"
set "_C_YELLOW=%_C_ESC%[33m"
set "_C_CYAN=%_C_ESC%[36m"
set "_C_BOLD=%_C_ESC%[1m"
exit /b 0

REM ====================== UI: step ======================
:ui_step
REM %~1 = label
set /a _UI_CUR=_UI_CUR+1
set "_UI_CUR_LABEL=%~1"
set /a _UI_PCT=_UI_CUR*100/_UI_TOTAL
set "_UI_T0=%TIME%"
echo.
echo ^>^> [%_UI_CUR%/%_UI_TOTAL%] %~1 ^(%_UI_PCT%%%^)
call :_ui_progress_bar %_UI_PCT%
if defined LOG echo [STEP %TIME%] [%_UI_CUR%/%_UI_TOTAL%] %~1 >> "%LOG%"
exit /b 0

REM ====================== UI: progress bar ======================
:_ui_progress_bar
REM %~1 = pct (0-100)
set /a _UI_BAR_FILLED=%~1*30/100
set /a _UI_BAR_EMPTY=30-_UI_BAR_FILLED
set "_UI_BAR_STR="
for /l %%i in (1,1,%_UI_BAR_FILLED%) do set "_UI_BAR_STR=!_UI_BAR_STR!#"
for /l %%i in (1,1,%_UI_BAR_EMPTY%) do set "_UI_BAR_STR=!_UI_BAR_STR!-"
echo    [!_UI_BAR_STR!] %~1%%
exit /b 0

REM ====================== UI: ok ======================
:ui_ok
REM %~1 = optional note
call :_ui_elapsed
if "%~1"=="" (
    echo    !_C_GREEN![OK]!_C_RESET! done ^(!_UI_ELAPSED!s^)
) else (
    echo    !_C_GREEN![OK]!_C_RESET! %~1 ^(!_UI_ELAPSED!s^)
)
echo OK^|%_UI_CUR_LABEL%^|!_UI_ELAPSED! >> "%_UI_SUMMARY_FILE%"
if defined LOG echo [OK %TIME%] %_UI_CUR_LABEL% took !_UI_ELAPSED!s >> "%LOG%"
exit /b 0

REM ====================== UI: warn ======================
:ui_warn
echo    !_C_YELLOW![!!]!_C_RESET! %~1
if defined LOG echo [WARN %TIME%] %~1 >> "%LOG%"
exit /b 0

REM ====================== UI: ok with warn ======================
:ui_ok_warn
call :_ui_elapsed
echo    !_C_YELLOW![!!]!_C_RESET! %~1 ^(!_UI_ELAPSED!s^)
echo WARN^|%_UI_CUR_LABEL%^|!_UI_ELAPSED! >> "%_UI_SUMMARY_FILE%"
if defined LOG echo [WARN-OK %TIME%] %_UI_CUR_LABEL% took !_UI_ELAPSED!s >> "%LOG%"
exit /b 0

REM ====================== UI: fail ======================
:ui_fail
call :_ui_elapsed
echo    !_C_RED![X]!_C_RESET! %~1 ^(!_UI_ELAPSED!s^)
echo FAIL^|%_UI_CUR_LABEL%^|!_UI_ELAPSED! >> "%_UI_SUMMARY_FILE%"
if defined LOG echo [FAIL %TIME%] %_UI_CUR_LABEL% ^(%~1^) took !_UI_ELAPSED!s >> "%LOG%"
exit /b 0

REM ====================== UI: info ======================
:ui_info
echo    !_C_CYAN![i]!_C_RESET! %~1
if defined LOG echo [INFO %TIME%] %~1 >> "%LOG%"
exit /b 0

REM ====================== UI: summary ======================
:ui_summary
echo.
echo +------------------------------------------------------------+
echo ^|   部署摘要
echo +------------------------------------------------------------+
set "_UI_ANY_FAIL=0"
set "_UI_ANY_WARN=0"
if exist "%_UI_SUMMARY_FILE%" (
    for /f "usebackq tokens=1,2,3 delims=|" %%a in ("%_UI_SUMMARY_FILE%") do (
        if "%%a"=="OK"   echo    !_C_GREEN![OK]!_C_RESET! %%b ^(%%cs^)
        if "%%a"=="WARN" (echo    !_C_YELLOW![!!]!_C_RESET! %%b ^(%%cs^) & set "_UI_ANY_WARN=1")
        if "%%a"=="FAIL" (echo    !_C_RED![X]!_C_RESET!  %%b ^(%%cs^) & set "_UI_ANY_FAIL=1")
    )
    del "%_UI_SUMMARY_FILE%" >nul 2>nul
)
echo.
if "!_UI_ANY_FAIL!"=="1" (
    echo !_C_RED![X]!_C_RESET! 部署存在失败步骤，请查看上方日志
    exit /b 1
)
if "!_UI_ANY_WARN!"=="1" (
    echo !_C_YELLOW![!!]!_C_RESET! 部署完成（有警告）
    exit /b 0
)
echo !_C_GREEN![OK]!_C_RESET! 部署完成，一切就绪
exit /b 0

REM ====================== UI: elapsed helper ======================
:_ui_elapsed
if not defined _UI_T0 (set "_UI_ELAPSED=0" & exit /b 0)
call :_time_to_ms "%_UI_T0%" _UI_T0_MS
call :_time_to_ms "%TIME%"    _UI_T1_MS
set /a _UI_DIFF_MS=_UI_T1_MS-_UI_T0_MS
if !_UI_DIFF_MS! LSS 0 set /a _UI_DIFF_MS+=86400000
set /a _UI_ELAPSED=_UI_DIFF_MS/1000
exit /b 0

REM ====================== time parser: HH:MM:SS.cs -> ms ======================
:_time_to_ms
set "_TS=%~1"
for /f "tokens=1-4 delims=:., " %%a in ("%_TS%") do (
    set /a %~2=^(^(1%%a-100^)*3600 + ^(1%%b-100^)*60 + ^(1%%c-100^)^)*1000 + ^(1%%d-100^)*10
)
exit /b 0

REM ====================== system: PATH refresh from registry ======================
:refresh_path
set "_NEWPATH="
for /f "usebackq tokens=2*" %%A in (`reg query "HKLM\System\CurrentControlSet\Control\Session Manager\Environment" /v Path 2^>nul`) do set "_NEWPATH=%%B"
for /f "usebackq tokens=2*" %%A in (`reg query "HKCU\Environment" /v Path 2^>nul`) do set "_NEWPATH=!_NEWPATH!;%%B"
if defined _NEWPATH (
    set "PATH=!_NEWPATH!"
    if defined LOG echo [PATH-REFRESH %TIME%] done >> "%LOG%"
)
exit /b 0

REM ====================== locate: tools that may not be on PATH after winget ======================
REM Each :locate_<tool> probes well-known install paths AND falls back to a
REM recursive search under WinGet's package storage / Program Files. On
REM success it prepends the directory to PATH. Caller does
REM   call :locate_<tool>
REM   where <tool> >nul 2>nul
REM and decides what to do based on errorlevel.
REM
REM All hits are logged to %LOG% (if defined) so we can diagnose silent
REM mismatches without forcing the user to share their PATH.

:locate_node
where node >nul 2>nul && exit /b 0
if defined LOG echo [LOCATE-NODE %TIME%] starting probe >> "%LOG%"
for %%D in (
    "%ProgramFiles%\nodejs"
    "%ProgramFiles(x86)%\nodejs"
    "%LOCALAPPDATA%\Programs\nodejs"
    "%LOCALAPPDATA%\Microsoft\WinGet\Links"
) do (
    if exist "%%~D\node.exe" (
        if defined LOG echo [LOCATE-NODE]   static hit: %%~D >> "%LOG%"
        set "PATH=%%~D;!PATH!"
    )
)
where node >nul 2>nul && exit /b 0
call :_recursive_locate node.exe
exit /b 0

:locate_git
where git >nul 2>nul && exit /b 0
if defined LOG echo [LOCATE-GIT %TIME%] starting probe >> "%LOG%"
for %%D in (
    "%ProgramFiles%\Git\cmd"
    "%ProgramFiles(x86)%\Git\cmd"
    "%LOCALAPPDATA%\Programs\Git\cmd"
    "%LOCALAPPDATA%\Microsoft\WinGet\Links"
) do (
    if exist "%%~D\git.exe" (
        if defined LOG echo [LOCATE-GIT]   static hit: %%~D >> "%LOG%"
        set "PATH=%%~D;!PATH!"
    )
)
where git >nul 2>nul && exit /b 0
call :_recursive_locate git.exe
exit /b 0

:locate_ollama
where ollama >nul 2>nul && exit /b 0
if defined LOG echo [LOCATE-OLLAMA %TIME%] starting probe >> "%LOG%"
for %%D in (
    "%LOCALAPPDATA%\Programs\Ollama"
    "%ProgramFiles%\Ollama"
    "%LOCALAPPDATA%\Microsoft\WinGet\Links"
) do (
    if exist "%%~D\ollama.exe" (
        if defined LOG echo [LOCATE-OLLAMA]   static hit: %%~D >> "%LOG%"
        set "PATH=%%~D;!PATH!"
    )
)
where ollama >nul 2>nul && exit /b 0
call :_recursive_locate ollama.exe
exit /b 0

REM Best-effort recursive search for an exe under WinGet's storage and
REM Program Files. Slow but bulletproof — only invoked when static probes fail.
:_recursive_locate
set "_LOC_EXE=%~1"
for %%R in (
    "%LOCALAPPDATA%\Microsoft\WinGet\Packages"
    "%ProgramFiles%\WinGet\Packages"
    "%ProgramFiles%"
    "%ProgramFiles(x86)%"
    "%LOCALAPPDATA%\Programs"
) do (
    if exist "%%~R" (
        for /f "delims=" %%F in ('where /R "%%~R" "!_LOC_EXE!" 2^>nul') do (
            if not defined _LOC_HIT (
                set "_LOC_HIT=%%F"
                if defined LOG echo [LOCATE]   recursive hit: %%F >> "%LOG%"
                for %%P in ("%%F") do set "PATH=%%~dpP;!PATH!"
            )
        )
    )
)
set "_LOC_EXE="
set "_LOC_HIT="
exit /b 0

REM ====================== install winget itself ======================
REM Downloads the latest Microsoft.DesktopAppInstaller .msixbundle from
REM GitHub releases and installs via Add-AppxPackage. Used to bootstrap a
REM working winget on machines whose in-box winget is missing or too old
REM (e.g. v1.2 with corrupt source database). Sets WINGET_EXE on success.
REM Requires PowerShell + internet. exit /b 0 on success, 1 on failure.
:install_winget
where powershell >nul 2>nul
if errorlevel 1 (
    if defined LOG echo [INSTALL-WINGET] no powershell available >> "%LOG%"
    exit /b 1
)
set "_WG_TMP=%TEMP%\AppInstaller_%RANDOM%.msixbundle"
set "_WG_URL_FILE=%TEMP%\winget_url_%RANDOM%.txt"
if defined LOG echo [INSTALL-WINGET %TIME%] querying GitHub for latest release URL >> "%LOG%"
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$ErrorActionPreference='Stop'; $ProgressPreference='SilentlyContinue'; [Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12; $r = Invoke-RestMethod 'https://api.github.com/repos/microsoft/winget-cli/releases/latest'; $u = ($r.assets | Where-Object { $_.name -like '*.msixbundle' } | Select-Object -First 1).browser_download_url; if (-not $u) { throw 'no msixbundle' }; Set-Content -Path '%_WG_URL_FILE%' -Value $u -NoNewline" 2>> "%LOG%"
if not exist "%_WG_URL_FILE%" (
    if defined LOG echo [INSTALL-WINGET] URL fetch failed >> "%LOG%"
    exit /b 1
)
set "_WG_URL="
set /p _WG_URL=<"%_WG_URL_FILE%"
del "%_WG_URL_FILE%" >nul 2>nul
if not defined _WG_URL (
    if defined LOG echo [INSTALL-WINGET] empty URL >> "%LOG%"
    exit /b 1
)
if defined LOG echo [INSTALL-WINGET] URL=!_WG_URL! >> "%LOG%"
REM Download with visible progress. Prefer curl.exe (Win10 1803+, has built-in
REM progress bar). Fall back to BITS / Invoke-WebRequest in PowerShell.
set "_WG_DL_OK=0"
where curl.exe >nul 2>nul
if not errorlevel 1 (
    echo     ^>^> downloading via curl ^(showing progress^) ...
    curl.exe -L --progress-bar -o "%_WG_TMP%" "!_WG_URL!"
    if exist "%_WG_TMP%" set "_WG_DL_OK=1"
)
if "!_WG_DL_OK!"=="0" (
    echo     ^>^> downloading via PowerShell BITS ^(showing progress^) ...
    powershell -NoProfile -ExecutionPolicy Bypass -Command ^
      "$ErrorActionPreference='Stop'; [Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12; try { Import-Module BitsTransfer -ErrorAction Stop; Start-BitsTransfer -Source '!_WG_URL!' -Destination '%_WG_TMP%' -Description 'winget' } catch { Write-Host 'BITS unavailable, using Invoke-WebRequest'; Invoke-WebRequest -Uri '!_WG_URL!' -OutFile '%_WG_TMP%' }"
    if exist "%_WG_TMP%" set "_WG_DL_OK=1"
)
if "!_WG_DL_OK!"=="0" (
    if defined LOG echo [INSTALL-WINGET] download failed >> "%LOG%"
    exit /b 1
)
if defined LOG for %%S in ("%_WG_TMP%") do echo [INSTALL-WINGET] downloaded %%~zS bytes >> "%LOG%"
echo     ^>^> installing via Add-AppxPackage ...
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$ErrorActionPreference='Stop'; Add-AppxPackage -Path '%_WG_TMP%' -ForceApplicationShutdown" >> "%LOG%" 2>&1
set "_AP_RC=%ERRORLEVEL%"
del "%_WG_TMP%" >nul 2>nul
if not "%_AP_RC%"=="0" (
    if defined LOG echo [INSTALL-WINGET] Add-AppxPackage rc=%_AP_RC% >> "%LOG%"
    exit /b 1
)
REM Re-detect winget after install
set "WINGET_EXE="
if exist "%LOCALAPPDATA%\Microsoft\WindowsApps\winget.exe" set "WINGET_EXE=%LOCALAPPDATA%\Microsoft\WindowsApps\winget.exe"
if not defined WINGET_EXE (
    for /f "delims=" %%W in ('where winget 2^>nul') do if not defined WINGET_EXE set "WINGET_EXE=%%W"
)
if not defined WINGET_EXE (
    if defined LOG echo [INSTALL-WINGET] post-install detect failed >> "%LOG%"
    exit /b 1
)
if defined LOG echo [INSTALL-WINGET] success: !WINGET_EXE! >> "%LOG%"
exit /b 0

REM ====================== system: find real Python ======================
:find_python
set "PY_EXE="
for /f "delims=" %%P in ('where python 2^>nul') do (
    if not defined PY_EXE (
        call :_is_real_python "%%P" _IS_REAL
        if "!_IS_REAL!"=="1" set "PY_EXE=%%P"
    )
)
if defined PY_EXE exit /b 0
where py >nul 2>nul
if not errorlevel 1 (
    for /f "delims=" %%P in ('py -3 -c "import sys;print(sys.executable)" 2^>nul') do if not defined PY_EXE set "PY_EXE=%%P"
)
if defined PY_EXE exit /b 0
for /d %%D in ("%LOCALAPPDATA%\Programs\Python\Python3*") do (
    if exist "%%D\python.exe" if not defined PY_EXE set "PY_EXE=%%D\python.exe"
)
if defined PY_EXE exit /b 0
REM Last resort: scan WinGet packages and Program Files trees.
if defined LOG echo [LOCATE-PYTHON %TIME%] starting recursive probe >> "%LOG%"
for %%R in (
    "%LOCALAPPDATA%\Microsoft\WinGet\Packages"
    "%ProgramFiles%\Python311"
    "%ProgramFiles%\Python312"
    "%ProgramFiles%\Python313"
) do (
    if exist "%%~R" (
        for /f "delims=" %%F in ('where /R "%%~R" python.exe 2^>nul') do (
            if not defined PY_EXE (
                call :_is_real_python "%%F" _IS_REAL
                if "!_IS_REAL!"=="1" (
                    set "PY_EXE=%%F"
                    if defined LOG echo [LOCATE-PYTHON]   recursive hit: %%F >> "%LOG%"
                )
            )
        )
    )
)
exit /b 0

REM Judge if %~1 is a real Python (vs Microsoft Store 0-byte stub)
:_is_real_python
set "%~2=0"
echo %~1 | findstr /i "WindowsApps" >nul
if not errorlevel 1 (
    for %%F in ("%~1") do if %%~zF LEQ 1024 exit /b 0
)
set "%~2=1"
exit /b 0

REM ============================================================
REM 加载完成标签 —— 被 call 时从 goto :_common_loaded 跳到此处
REM ============================================================
:_common_loaded
exit /b 0
